export const NOTIFICATION_TEMPLATE_VERSION='4.4';
const line=value=>String(value||'').trim();
const jobName=context=>[line(context.company),line(context.role)].filter(Boolean).join(' — ')||'workflow de Career Ops';
const footer=context=>context.sheetUrl?`\n\nAbrir TODAY:\n${context.sheetUrl}`:'';

export function renderActionableNotification(type, context = {}) {
  const job=jobName(context),blocker=line(context.humanBlocker)||'Se necesita una respuesta personal para continuar.';
  const templates={
    NEEDS_HUMAN:{subject:`Career Ops necesita tu respuesta — ${line(context.company)||'aplicación'}`,body:`${job}\nEstado: WAITING_FOR_YOU\n\nCareer Ops necesita:\n${blocker}\n\nSiguiente acción:\n${line(context.recommendedAction)||'Abre TODAY, responde la pregunta y usa Sync Jobs.'}`},
    READY_FOR_REVIEW:{subject:`Paquete de aplicación listo — ${line(context.company)||'oportunidad'}`,body:`${job}\n\nCareer Ops completó la preparación del paquete.\nRecomendación: ${line(context.recommendation)||'REVISAR'}\n\nSiguiente acción:\nAbre TODAY y revisa el resume, cover letter y application plan.`},
    APPLICATION_CONFIRMED:{subject:`Aplicación confirmada — ${line(context.company)||'oportunidad'}`,body:`${job}\nCanal: ${line(context.channel)||'ATS'}\nConfirmada: ${line(context.localTime)||'ahora'}\n\nCareer Ops movió este trabajo a APPLICATIONS.`},
    APPLICATION_FAILED:{subject:`Career Ops necesita atención — aplicación`,body:`${job}\nEstado: FAILED\n\nCareer Ops no pudo completar la aplicación.\nSiguiente acción:\n${line(context.recommendedAction)||'Abre TODAY y revisa Last Activity antes de volver a intentar.'}`},
    OUTREACH_FAILED:{subject:`Career Ops necesita atención — outreach`,body:`${job}\nEstado de outreach: FAILED\n\nNo se reintentará automáticamente.\nSiguiente acción:\n${line(context.recommendedAction)||'Abre APPLICATIONS o CONTACTS y revisa el resultado.'}`},
    OUTREACH_VERIFICATION_REQUIRED:{subject:`Verifica el outreach — ${line(context.company)||'aplicación'}`,body:`${job}\nEstado: VERIFICATION_REQUIRED\n\nEl resultado de entrega es ambiguo y Career Ops no lo repetirá.\nSiguiente acción:\nVerifica el canal antes de autorizar otra acción.`},
    EXTERNAL_ACTION_REQUIRED:{subject:`Career Ops necesita tu acción — ${line(context.company)||'workflow'}`,body:`${job}\nEstado: NEEDS_YOU\n\n${blocker}\n\nSiguiente acción:\n${line(context.recommendedAction)||'Abre TODAY y completa la acción externa indicada.'}`},
    RESPONSE_RECEIVED:{subject:`Respuesta recibida — ${line(context.company)||'oportunidad'}`,body:`${job}\n\nCareer Ops detectó una respuesta al outreach autorizado. No responderá automáticamente.\nSiguiente acción:\nAbre APPLICATIONS y decide la respuesta.`},
    COMMAND_FAILED:{subject:`Career Ops necesita atención — ${line(context.commandLabel)||'comando'}`,body:`${line(context.commandLabel)||'El comando solicitado'} no pudo completarse.\nEstado: FAILED\n\nSiguiente acción:\nAbre TODAY o SETTINGS y revisa el resultado del comando.`},
    ENRICHMENT_BLOCKED:{subject:`Career Ops necesita atención — preparación`,body:`${job}\nEtapa: PREPARING\nEstado: BLOCKED\n\nCareer Ops no pudo completar la preparación.\nSiguiente acción:\n${line(context.recommendedAction)||'Abre TODAY y revisa el motivo del bloqueo.'}`},
    COMMUNITY_NEEDS_HUMAN:{subject:`Career Ops necesita tu respuesta — comunidad`,body:`${line(context.communityName)||'Una comunidad autorizada'} necesita una respuesta para continuar el proceso de ingreso.\n\nSiguiente acción:\nAbre COMMUNITIES y revisa el blocker.`},
    OPERATIONAL_ESCALATION:{subject:`Career Ops necesita atención — ${['AUTH_FAILURE','WORKSPACE_AUTH_FAILED'].includes(context.operationalSignalType)?'autenticación de Workspace':line(context.component)||'operación'}`,body:`${['AUTH_FAILURE','WORKSPACE_AUTH_FAILED'].includes(context.operationalSignalType)?`Falló la autenticación de Google Workspace (${line(context.technicalDetail)||'capa no identificada'}).\n\nCareer Ops intentó:\n- generar una credencial nueva en el broker headless\n- verificar acceso al Sheet\n\nAfecta:\n- Google Sheets y sus proyecciones\n\nSigue operativo:\n- receptor de comandos\n- Candidate Gmail\n- automatización de navegador`:context.operationalSignalType==='SUBSCRIBER_DOWN'?'Career Ops intentó reiniciar el receptor de comandos y no pudo verificarlo.':'Career Ops diagnosticó la condición y agotó la recuperación segura.'}\n\nSiguiente acción:\n${line(context.recommendedAction)||'Abre SETTINGS y revisa el componente indicado.'}`},
    DAILY_COMPLETION_SUMMARY:{subject:'Career Ops — resumen de búsqueda de hoy',body:`Embudo de hoy\n\nRevisadas: ${Number(context.reviewed)||0}\nNuevas observaciones: ${Number(context.newJobs)||0}\nPasaron elegibilidad: ${Number(context.passed)||0}\nShortlist/preselección: ${Number(context.shortlisted)||0}\nEvaluadas con APPLY: ${Number(context.promoted)||0}\nPipeline fuerte: ${Number(context.pipelineStrong)||0}\nTODAY desde Pipeline: ${Number(context.todayCurated)||0}\nCarryovers humanos: ${Number(context.humanCarryovers)||0}\nEn TODAY total: ${Number(context.today)||0}\nNecesitan tu atención: ${Number(context.attention)||0}\nAplicaciones confirmadas: ${Number(context.applicationsConfirmed)||0}${context.topThree?.length?`\n\nTop de TODAY / Pipeline\n${context.topThree.map(item=>`${item.rank}. ${item.company} — ${item.role} · ${item.stage} · ${item.recommendation}`).join('\n')}`:'\n\nTop de TODAY / Pipeline\nSin oportunidades fuertes todavía.'}\n\nSistema: ${line(context.systemStatus)||'UNKNOWN'} · Fallos sin resolver: ${Number(context.unresolvedFailures)||0}${Number(context.limitedSources)>0?` · Fuentes limitadas: ${Number(context.limitedSources)}`:''}`},
    WORKFLOW_DIGEST:{subject:`Career Ops terminó la preparación — ${Number(context.attention)||0} requieren tu atención`,body:`Career Ops ${context.runStatus==='PARTIAL'?'terminó esta iteración con algunas limitaciones.':'terminó esta iteración.'}\n\nProcesadas: ${Number(context.processed)||0}\nWAITING_FOR_YOU: ${Number(context.attention)||0}${Number(context.ready)>0?`\n• ${Number(context.ready)} READY para revisión`:''}${Number(context.answers)>0?`\n• ${Number(context.answers)} necesitan una respuesta`:''}${Number(context.verification)>0?`\n• ${Number(context.verification)} requieren verificación`:''}${Number(context.blocked)>0?`\n• ${Number(context.blocked)} bloqueadas`:''}${Number(context.failed)>0?`\n• ${Number(context.failed)} con fallo`:''}${Number(context.noAction)>0?`\n\nSin intervención: ${Number(context.noAction)}`:''}${context.items?.length?`\n\nPrioridad:\n${context.items.map(item=>`- ${item.company} — ${item.attentionType}`).join('\n')}`:''}${Number(context.more)>0?`\n+ ${Number(context.more)} más en TODAY`:''}\n\nSiguiente acción:\nAbre TODAY y atiende los elementos WAITING_FOR_YOU.`},
    APPLICATION_BATCH_DIGEST:{subject:context.blocked?.length?`Career Ops necesita ${context.blocked.length} ${context.blocked.length===1?'acción breve':'acciones breves'}`:`Career Ops completó ${context.applied?.length||0} ${(context.applied?.length||0)===1?'aplicación':'aplicaciones'}`,body:`Career Ops terminó el lote y conserva la responsabilidad de cada aplicación.${context.applied?.length?`\n\nAPLICADAS\n${context.applied.map(item=>`- ${item.company} — confirmada`).join('\n')}`:''}${context.blocked?.length?`\n\nNECESITA TU AYUDA\n${context.blocked.map(item=>`- ${item.company}: ${item.action}${item.questionCount?` (${item.questionCount} respuestas)`:''}${item.instruction?`\n  ${item.instruction}`:''}`).join('\n')}`:''}${context.failed?.length?`\n\nNO COMPLETADAS\n${context.failed.map(item=>`- ${item.company} — Career Ops registró el fallo y no repetirá un envío ambiguo.`).join('\n')}`:''}\n\nTODAY\n- ${Number(context.todayPromoted)||0} oportunidades nuevas promovidas\n- ${context.blocked?.length||0} ayudas breves pendientes\n\nNo completes aplicaciones manualmente; realiza sólo la acción indicada y Career Ops continuará.`},
    DELIVERY_PROBE:{subject:'Career Ops notification test',body:'Career Ops V3D notification delivery is working.'},
  };
  const selected=templates[type];if(!selected)throw new TypeError(`unknown notification template: ${type}`);
  return {subject:selected.subject,text:`${selected.body}${footer(context)}`,templateVersion:NOTIFICATION_TEMPLATE_VERSION};
}
