import { mkdirSync, writeFileSync } from 'fs';
import path from 'path';
import { hashStable } from '../acquisition/normalize.mjs';
import { renderTextPdf } from './text-pdf.mjs';

const safe = value => String(value || '').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._ -]+/g, '').replace(/\s+/g,' ').trim().slice(0,80) || 'Application';
const storageSafe = value => safe(value).replace(/\s+/g,'-').toLowerCase();
const renderSourced = item => String(item?.text || '').trim();
export function shortRoleLabel(title='') { const value=String(title);for(const pattern of [/Solutions Architect/i,/AI Solutions Engineer/i,/AI Engineer/i,/Data Engineer/i,/Systems Engineer/i,/Software Engineer/i,/Product Manager/i,/Project Manager/i]){const match=value.match(pattern);if(match)return match[0].replace(/\b\w/g,c=>c.toUpperCase()).replace(/Ai\b/,'AI');}return safe(value.replace(/\([^)]*\)/g,'').replace(/\b(?:senior|sr\.?|lead|leader|pre-sales|staff|principal)\b/gi,'')).split(' ').slice(0,4).join(' ')||'Application'; }

function composeResume({job,packageRecord,canonicalCv}) {
  const source=String(canonicalCv||'').trim();const lines=source.split(/\r?\n/);const firstSection=lines.findIndex(line=>/^##\s+/.test(line));const core=lines.findIndex(line=>/^##\s+Core Competencies\s*$/i.test(line));if(firstSection<0||core<0)throw new Error('canonical CV lacks required professional structure');
  const identity=lines.slice(0,firstSection).join('\n').trim();const body=lines.slice(core).join('\n').trim();const summary=renderSourced(packageRecord?.artifacts?.resume_variant?.summary);const role=shortRoleLabel(job.title);
  return `${identity}\n\n## ${role}\n\n${summary}\n\n${body}\n`;
}

export function validateRenderedResume({markdown,pdf,candidateName='Jorge Vera'}={}) {
  const errors=[];const value=String(markdown||'');if(/Canonical CV|unchanged source|evidence[- ]backed|candidate knowledge|evidence_refs/i.test(value))errors.push('internal composition terminology is visible');if(!/^##\s+Professional Experience\s*$/m.test(value))errors.push('professional experience is missing');if((value.match(/^###\s+/gm)||[]).length<5)errors.push('resume is too sparse');if(!value.includes(candidateName))errors.push('candidate identity is missing');if((value.match(new RegExp(candidateName.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'g'))||[]).length>1)errors.push('candidate identity is duplicated');if(new RegExp(`${candidateName.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\s+(?:brings|has|is)\\b`,'i').test(value))errors.push('third-person generated biography is not allowed');const pages=Buffer.isBuffer(pdf)?Number((pdf.toString('latin1').match(/\/Type \/Page\b/g)||[]).length):0;if(!pdf||pages<1)errors.push('ATS-readable PDF was not generated');if(pages>2)errors.push(`resume exceeds two pages: ${pages}`);return{valid:!errors.length,errors,pages};
}

export function validateRenderedCoverLetter({markdown,company,role,candidateName='Jorge Vera'}={}) { const value=String(markdown||'');const body=value.replace(/^#.*$/gm,'').trim();const words=body.split(/\s+/).filter(Boolean).length;const errors=[];if(words<180||words>300)errors.push(`cover letter must be 180-300 words; observed ${words}`);if(!/\b(?:I|my|me)\b/i.test(body))errors.push('cover letter is not first person');if(!value.includes(company)||!value.includes(role))errors.push('cover letter is not role/company specific');if(/evidence[- ]backed|canonical evidence|candidate knowledge|evidence_refs|unchanged source/i.test(value))errors.push('internal terminology is visible');if(new RegExp(`${candidateName.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\s+(?:brings|has|is)\\b`,'i').test(value))errors.push('third-person self-reference is not allowed');return{valid:!errors.length,errors,words}; }

export class ApplicationArtifactWriter {
  constructor({root='output/applications'}={}){this.root=path.resolve(root);}
  write({job,packageRecord=null,canonicalCv='',applicationPlan,contactPlan,activationPlan=null,researchReport,coverLetterRequired=true}={}){
    const version=packageRecord?.packageVersion||null,artifactVersion=packageRecord?`v${version}`:`review-${hashStable(JSON.stringify(researchReport||{})).slice(0,12)}`,directory=path.join(this.root,storageSafe(job.id||job.jobId),artifactVersion);if(!directory.startsWith(`${this.root}${path.sep}`))throw new Error('artifact path escaped configured root');mkdirSync(directory,{recursive:true});
    const artifacts=packageRecord?.artifacts||{},files={};const put=(key,filename,content,type)=>{const target=path.join(directory,filename);writeFileSync(target,content,{mode:0o600});files[key]={path:target,filename,humanFilename:filename,hash:hashStable(content),bytes:Buffer.byteLength(content),type,version};};
    if(artifacts.resume_variant){const resumeText=composeResume({job,packageRecord,canonicalCv}),resumePdf=renderTextPdf(resumeText),resumeName=`Jorge Vera - ${shortRoleLabel(job.title)}.pdf`,quality=validateRenderedResume({markdown:resumeText,pdf:resumePdf});if(!quality.valid)throw Object.assign(new Error(`resume quality gate failed: ${quality.errors.join('; ')}`),{code:'RESUME_QUALITY_FAILED',quality});put('resume.md','resume.md',resumeText,'RESUME_SOURCE');put('resume.pdf',resumeName,resumePdf,'RESUME');}
    if(coverLetterRequired&&artifacts.cover_letter?.content){const coverText=`# Jorge Vera\n\njorgeaveraf@gmail.com | +52 2727038197 | Orizaba, Ver. MX\n\n## Cover Letter — ${job.title} at ${job.company}\n\nDear Hiring Team,\n\n${artifacts.cover_letter.content.trim()}\n\nSincerely,\n\nJorge Vera\n`,quality=validateRenderedCoverLetter({markdown:coverText,company:job.company,role:job.title});if(!quality.valid)throw Object.assign(new Error(`cover letter quality gate failed: ${quality.errors.join('; ')}`),{code:'COVER_LETTER_QUALITY_FAILED',quality});const coverName=`Jorge Vera - ${shortRoleLabel(job.title)} - Cover Letter.pdf`;put('cover-letter.md','cover-letter.md',coverText,'COVER_LETTER_SOURCE');put('cover-letter.pdf',coverName,renderTextPdf(coverText),'COVER_LETTER');}
    put('application-plan.json','application-plan.json',`${JSON.stringify(applicationPlan,null,2)}\n`,'APPLICATION_PLAN');put('contact-plan.json','contact-plan.json',`${JSON.stringify(contactPlan,null,2)}\n`,'CONTACT_PLAN');if(activationPlan?.outreachPlan)put('outreach-plan.json','outreach_plan.json',`${JSON.stringify(activationPlan.outreachPlan,null,2)}\n`,'OUTREACH_PLAN');put('research-report.json','research-report.json',`${JSON.stringify(researchReport,null,2)}\n`,'RESEARCH_REPORT');
    const summary=`# Application Review Package\n\n- Company: ${job.company}\n- Role: ${job.title}\n- Recommendation: ${packageRecord?'APPLY':'DO_NOT_APPLY / CONSIDER'}\n- Resume: ${files['resume.pdf']?.humanFilename||'NOT_GENERATED'}\n- Cover letter: ${files['cover-letter.pdf']?.humanFilename||(coverLetterRequired?'NOT_GENERATED':'NOT_NEEDED')}\n- Application path: ${applicationPlan.primaryPath}\n- Contact plan: ${contactPlan.status}\n\nNo application or outreach was executed.\n`;put('README.md','README.md',summary,'PACKAGE_INDEX');
    return{version:'2.1',directory,packageVersion:version,resumeStatus:files['resume.pdf']?'READY':'NOT_GENERATED',coverLetterStatus:files['cover-letter.pdf']?'READY':coverLetterRequired?'NOT_GENERATED':'NOT_NEEDED',activationStatus:activationPlan?.status||'NOT_PLANNED',files};
  }
}
