export const APPLICATION_ENRICHMENT_VERSION = '2B.1';
export const APPLICATION_ENRICHMENT_STATUSES = Object.freeze([
  'PENDING', 'RESEARCHING', 'EVALUATING', 'GENERATING_PACKAGE',
  'READY_FOR_REVIEW', 'BLOCKED', 'FAILED', 'CANCELLED',
]);
export const APPLICATION_PATH_TYPES = Object.freeze(['ATS', 'EMAIL', 'PLATFORM', 'RECRUITER_CONTACT', 'OTHER', 'UNKNOWN']);
export const ENRICHMENT_FAILURE_CODES = Object.freeze([
  'RESEARCH_BLOCKED', 'INSUFFICIENT_EVIDENCE', 'EVALUATION_DO_NOT_APPLY',
  'PACKAGE_FAILED', 'LLM_FAILED', 'AUTH_REQUIRED', 'CHALLENGE',
  'CAPTCHA', 'SOURCE_UNAVAILABLE', 'EVIDENCE_IDENTITY_UNCERTAIN',
]);
export const DEFAULT_APPLICATION_RESEARCH_BUDGET = Object.freeze({
  maxBrowserMinutes: 12, maxPages: 8, maxSearchQueries: 6,
  maxContactCandidates: 5, maxRetries: 1, maxLlmCalls: 2,
});
export const ENRICHMENT_TRANSITIONS = Object.freeze({
  PENDING: Object.freeze(['RESEARCHING', 'CANCELLED']),
  RESEARCHING: Object.freeze(['EVALUATING', 'BLOCKED', 'FAILED', 'CANCELLED']),
  EVALUATING: Object.freeze(['GENERATING_PACKAGE', 'READY_FOR_REVIEW', 'BLOCKED', 'FAILED', 'CANCELLED']),
  GENERATING_PACKAGE: Object.freeze(['READY_FOR_REVIEW', 'BLOCKED', 'FAILED', 'CANCELLED']),
  READY_FOR_REVIEW: Object.freeze(['PENDING', 'RESEARCHING', 'CANCELLED']),
  BLOCKED: Object.freeze(['PENDING', 'CANCELLED']),
  FAILED: Object.freeze(['PENDING', 'CANCELLED']),
  CANCELLED: Object.freeze([]),
});
