import { DEFAULT_OPERATIONAL_THRESHOLDS, signalDedupeKey } from './contracts.mjs';
import { RecoverySafetyClassifier } from './policy.mjs';

const age=(now,value)=>value?Math.max(0,new Date(now).getTime()-new Date(value).getTime()):Infinity;
const make=(input,classifier)=>{const enriched={aggregateType:'OPERATIONAL_RUN',correlationId:`operational:${input.signalType.toLowerCase()}:${input.aggregateId}`,...input};enriched.safetyClass=input.safetyClass||classifier.classify(enriched);enriched.dedupeKey=signalDedupeKey(enriched);return enriched;};

export function detectOperationalSignals(snapshot={}, {thresholds=DEFAULT_OPERATIONAL_THRESHOLDS,classifier=new RecoverySafetyClassifier()}={}){
  const now=snapshot.now||new Date().toISOString(),signals=[];const startupEvidence=snapshot.startup?.active?[{type:'startupGrace',id:`uptime:${Math.round(snapshot.startup.uptimeMs)}ms`}]:[];const add=input=>signals.push(make({...input,evidenceRefs:[...(input.evidenceRefs||[]),...startupEvidence]},classifier));
  const subscriber=snapshot.subscriber||{};
  if(!subscriber.loaded||!subscriber.running)add({signalType:'SUBSCRIBER_DOWN',severity:'ERROR',component:'command-subscriber',aggregateId:'com.careerops.command-subscriber',summary:'Native command subscriber is not running.',evidenceRefs:[{type:'launchAgent',id:'com.careerops.command-subscriber'}],recommendedAction:'Career Ops agotó el reinicio automático del receptor. Mantén iniciada la sesión del Mac y abre SETTINGS para confirmar Command Subscriber.',autoRecoverable:true,remediationAction:'RESTART_COMMAND_SUBSCRIBER'});
  for(const agent of snapshot.launchAgents||[]){if(agent.label==='com.careerops.command-subscriber')continue;if(!agent.plistExists||!agent.loaded)add({signalType:'LAUNCHAGENT_DOWN',severity:'ERROR',component:'launchagent',aggregateId:agent.label,summary:`Required LaunchAgent ${agent.label} is ${!agent.plistExists?'missing':'unloaded'}.`,evidenceRefs:[{type:'launchAgent',id:agent.label}],recommendedAction:'Bootstrap the canonical plist and verify it is loaded.',autoRecoverable:Boolean(agent.plistExists),remediationAction:agent.plistExists?'RESTART_LAUNCHAGENT':null});else if(agent.recentRestartCount>=thresholds.flapThreshold&&agent.lastExitCode!==0)add({signalType:'LAUNCHAGENT_DOWN',severity:'ERROR',component:'launchagent',aggregateId:agent.label,summary:`LaunchAgent ${agent.label} is crash-looping.`,evidenceRefs:[{type:'launchAgent',id:agent.label}],recommendedAction:'Inspect the private launchd log; automatic restart is bounded.',autoRecoverable:true,remediationAction:'RESTART_LAUNCHAGENT',flapping:true});}
  for(const command of snapshot.commands||[]){if(['RECEIVED','PROCESSING'].includes(command.status)&&age(now,command.startedAt||command.receivedAt)>thresholds.commandMs&&!command.terminalEvent)add({signalType:'COMMAND_STUCK',severity:'ERROR',component:'workflow-command',aggregateType:'COMMAND',aggregateId:command.commandId,correlationId:command.correlationId,causationId:command.lastEventId||command.commandId,summary:`${command.commandType} command is stuck in ${command.status}.`,evidenceRefs:[{type:'commandId',id:command.commandId}],recommendedAction:'Resume the idempotent command once from authoritative state.',autoRecoverable:true,remediationAction:'RECOVER_ORPHANED_COMMAND'});}
  for(const item of snapshot.workflowStages||[]){const threshold=item.stage==='PREPARE'?thresholds.prepareMs:item.stage==='APPLY'?thresholds.applyMs:item.stage==='COMMUNITY'?thresholds.communityMs:thresholds.commandMs;if(item.workflowStatus==='PROCESSING'&&age(now,item.lastUpdated)>threshold&&!item.waitingForHuman)add({signalType:'WORKFLOW_STUCK',severity:'ERROR',component:'workflow',aggregateId:item.aggregateId,aggregateType:item.aggregateType||'JOB',correlationId:item.correlationId||`workflow:${item.aggregateId}`,summary:`${item.stage} workflow has no meaningful progress.`,evidenceRefs:[{type:'aggregateId',id:item.aggregateId}],recommendedAction:'Inspect authoritative stage ownership before any recovery.',autoRecoverable:false});}
  for(const item of snapshot.enrichments||[]){if(['RESEARCHING','EVALUATING','GENERATING_PACKAGE'].includes(item.status)&&item.claimExpiresAt&&new Date(item.claimExpiresAt)<new Date(now))add({signalType:'ENRICHMENT_STUCK',severity:'ERROR',component:'application-enrichment',aggregateType:'ENRICHMENT',aggregateId:item.id,correlationId:item.correlationId||`enrichment:${item.id}`,summary:`Enrichment ${item.id} has an expired lease in ${item.status}.`,evidenceRefs:[{type:'enrichmentRequestId',id:item.id}],recommendedAction:'Return the expired internal lease to PENDING.',autoRecoverable:true,remediationAction:'REQUEUE_SAFE_ENRICHMENT'});}
  for(const queue of snapshot.workerQueues||[]){if(queue.queueDepth>0&&age(now,queue.oldestQueuedAt)>10000)add({signalType:'WORKER_QUEUE_STALE',severity:'ERROR',component:queue.worker,aggregateType:'WORK_ITEM',aggregateId:queue.workType,summary:`${queue.queueDepth} ${queue.workType.toLowerCase()} item(s) exceeded the 10 second claim SLA.`,evidenceRefs:[{type:'workType',id:queue.workType},{type:'oldestQueuedAt',id:queue.oldestQueuedAt}],recommendedAction:'Wake the authoritative worker once and verify that the queue is claimed.',autoRecoverable:true,remediationAction:'WAKE_EXECUTION_WORKER'});}
  for(const item of snapshot.applications||[]){if(item.verificationUnknown||item.blockerCode==='VERIFICATION_UNKNOWN')add({signalType:'APPLICATION_VERIFICATION_UNKNOWN',severity:'CRITICAL',component:'application-execution',aggregateType:'APPLICATION',aggregateId:item.id,correlationId:item.correlationId||`application:${item.id}`,summary:'Application submission outcome is ambiguous and must be verified by a human.',evidenceRefs:[{type:'applicationId',id:item.id}],recommendedAction:'Verify externally; never click submit again automatically.',autoRecoverable:false,externalMutationObserved:true,notificationSuppressed:Boolean(item.lifecycleNotificationExists)});else if(item.status==='EXECUTING'&&age(now,item.updatedAt||item.startedAt)>thresholds.applyMs)add({signalType:'APPLICATION_EXECUTION_STUCK',severity:item.externalMutationObserved?'CRITICAL':'ERROR',component:'application-execution',aggregateType:'APPLICATION',aggregateId:item.id,correlationId:item.correlationId||`application:${item.id}`,summary:`Application execution is stuck at ${item.stage||'unknown stage'}.`,evidenceRefs:[{type:'applicationId',id:item.id}],recommendedAction:item.externalMutationObserved?'Inspect external state; do not repeat submission.':'Review the exact authorization before resuming.',autoRecoverable:false,externalMutationObserved:Boolean(item.externalMutationObserved)});}
  for(const run of snapshot.orphanedRuns||[])add({signalType:'ORPHANED_OPERATIONAL_RUN',severity:'ERROR',component:'operational-run',aggregateId:run.id,correlationId:run.correlationId||run.id,summary:`Operational run ${run.id} is orphaned in ${run.status}.`,evidenceRefs:[{type:'runId',id:run.id}],recommendedAction:'Close the dead internal run canonically.',autoRecoverable:true,remediationAction:'RECOVER_ORPHANED_RUN'});
  if(snapshot.auth&&!snapshot.auth.ok)add({signalType:'WORKSPACE_AUTH_FAILED',severity:'ERROR',component:'workspace-auth',aggregateId:snapshot.auth.mode||'workspace-provider',summary:`Workspace authentication failed at ${snapshot.auth.code||'unknown'}.`,evidenceRefs:[{type:'authMode',id:snapshot.auth.mode||'unknown'},{type:'authProvider',id:snapshot.auth.provider||'unknown'},{type:'errorCode',id:snapshot.auth.code||'WORKSPACE_AUTH_FAILED'},{type:'affectedComponent',id:'google-sheets'}],recommendedAction:'Administrador de Brunova: confirma que career-ops-workspace-auth-broker conserva acceso al secreto, signBlob sobre brunova-knowledge-agent y la autorización DWD de Sheets para brunova@brunova.mx.',autoRecoverable:true,remediationAction:'RETRY_GOOGLE_AUTH'});
  if(snapshot.auth?.ok&&snapshot.sheet&&!snapshot.sheet.ok)add({signalType:'SHEET_SYNC_FAILURE',severity:snapshot.sheet.transient?'WARN':'ERROR',component:'google-sheets',aggregateId:snapshot.sheet.spreadsheetId||'control-plane',summary:`Google Sheets access/projection failed: ${snapshot.sheet.code||'unknown'}.`,evidenceRefs:[{type:'spreadsheetId',id:snapshot.sheet.spreadsheetId||'unknown'},{type:'errorCode',id:snapshot.sheet.code||'SHEET_ACCESS_FAILED'}],recommendedAction:snapshot.sheet.transient?'Reintentar sólo la proyección desde el estado autoritativo.':'Revisar autenticación o permisos.',autoRecoverable:true,remediationAction:'RETRY_SHEET_SYNC'});
  if(snapshot.gateway&&!snapshot.gateway.ok)add({signalType:'GATEWAY_UNHEALTHY',severity:'ERROR',component:'command-gateway',aggregateId:'career-ops-command-gateway',summary:'Cloud Run command gateway is unhealthy or unreachable.',evidenceRefs:[{type:'url',id:snapshot.gateway.url||'gateway'}],recommendedAction:'Inspect Cloud Run; no automatic rollback is allowed.',autoRecoverable:false});
  if(snapshot.pubsub?.available&&subscriber.running){const seconds=Number(snapshot.pubsub.oldestUnackedAgeSeconds||0);if(seconds>thresholds.pubsubWarnAgeSeconds)add({signalType:'PUBSUB_BACKLOG',severity:seconds>thresholds.pubsubErrorAgeSeconds?'ERROR':'WARN',component:'pubsub',aggregateId:snapshot.pubsub.subscription||'career-ops-local',summary:`Pub/Sub oldest unacked message is ${Math.round(seconds)} seconds old.`,evidenceRefs:[{type:'subscription',id:snapshot.pubsub.subscription||'career-ops-local'}],recommendedAction:'Verify subscriber consumption before changing cloud resources.',autoRecoverable:false});}
  const notifications=snapshot.notifications||{};if(notifications.ambiguous>0)add({signalType:'NOTIFICATION_PROVIDER_FAILURE',severity:'CRITICAL',component:'notifications',aggregateId:'ambiguous-send',summary:'At least one email delivery has an ambiguous provider outcome.',evidenceRefs:[],recommendedAction:'Inspect provider logs; never resend automatically.',autoRecoverable:false,notificationAmbiguous:true});else if(!notifications.providerReady)add({signalType:'NOTIFICATION_PROVIDER_FAILURE',severity:'ERROR',component:'notifications',aggregateId:'provider',summary:'Notification provider is not ready.',evidenceRefs:[],recommendedAction:'Inspect provider credentials/domain; do not rotate or change DNS automatically.',autoRecoverable:false});else if(notifications.pending>thresholds.notificationPendingCount||notifications.oldestPendingAgeMs>thresholds.notificationPendingAgeMs)add({signalType:'NOTIFICATION_BACKLOG',severity:'WARN',component:'notifications',aggregateId:'outbox',summary:`Notification outbox has ${notifications.pending} pending item(s).`,evidenceRefs:[],recommendedAction:'Drain only pending or scheduled transient deliveries.',autoRecoverable:true,remediationAction:'DRAIN_NOTIFICATION_OUTBOX'});
  if(snapshot.browserLock?.stale)add({signalType:'BROWSER_LOCK_STALE',severity:'WARN',component:'browser-session',aggregateId:snapshot.browserLock.path||'career-ops-browser-lock',summary:'Career Ops browser lock is expired and its owner process is not alive.',evidenceRefs:[{type:'lockPath',id:snapshot.browserLock.path||'unknown'}],recommendedAction:'Remove only the verified stale lock.',autoRecoverable:true,remediationAction:'CLEAR_STALE_BROWSER_LOCK'});
  for(const drift of snapshot.selectorDrift||[]){if(drift.consecutive>=thresholds.selectorDriftCount&&drift.runs>=2)add({signalType:'BROWSER_SELECTOR_DRIFT',severity:'WARN',component:'browser-source',aggregateId:drift.source,summary:`${drift.source} produced repeated SELECTOR_CHANGED outcomes.`,evidenceRefs:drift.runIds?.map(id=>({type:'runId',id}))||[],recommendedAction:'Degrade this source for the current run and review selectors manually.',autoRecoverable:true,remediationAction:'TEMPORARILY_DEGRADE_SOURCE'});}
  for(const spike of snapshot.challengeSpikes||[]){if(spike.count>=thresholds.challengeSpikeCount)add({signalType:'BROWSER_CHALLENGE_SPIKE',severity:'WARN',component:'browser-source',aggregateId:spike.source,summary:`${spike.source} produced repeated challenge/auth outcomes.`,evidenceRefs:spike.runIds?.map(id=>({type:'runId',id}))||[],recommendedAction:'Stop retrying this source for the current run; do not bypass the challenge.',autoRecoverable:true,remediationAction:'TEMPORARILY_DEGRADE_SOURCE'});}
  for(const failure of snapshot.providerFailures||[]){if(failure.count>=thresholds.providerFailureCount)add({signalType:'PROVIDER_FAILURE_SPIKE',severity:'WARN',component:'provider',aggregateId:failure.provider,summary:`${failure.provider} has ${failure.count} repeated deterministic failures.`,evidenceRefs:failure.runIds?.map(id=>({type:'runId',id}))||[],recommendedAction:'Temporarily skip the source for the current run; do not edit portals.yml.',autoRecoverable:true,remediationAction:'TEMPORARILY_DEGRADE_SOURCE'});}
  if(snapshot.watch?.required&&snapshot.auth?.ok&&(!snapshot.watch.ok||snapshot.watch.ageMs>thresholds.watchStaleMs))add({signalType:'OPERATIONAL_WATCH_FAILURE',severity:'ERROR',component:'operational-watch',aggregateId:'com.careerops.operational-watch',summary:`Operational watch failed its self-check${snapshot.watch.errorCode?`: ${snapshot.watch.errorCode}`:''}.`,evidenceRefs:[{type:'launchAgent',id:'com.careerops.operational-watch'},...(snapshot.watch.errorCode?[{type:'errorCode',id:snapshot.watch.errorCode}]:[])],recommendedAction:'Career Ops agotó el reinicio seguro del watcher. Mantén iniciada la sesión del Mac y abre SETTINGS para ver el componente que sigue degradado.',autoRecoverable:true,remediationAction:'RESTART_LAUNCHAGENT'});
  const today=snapshot.today||{};
  const pipeline=snapshot.pipeline||{};
  if(Number(pipeline.admissibleNotProjected||0)>0)add({signalType:'PIPELINE_ADMISSIBLE_NOT_PROJECTED',severity:'ERROR',component:'pipeline-admission',aggregateType:'PIPELINE',aggregateId:'strong-candidates',summary:'A strong admissible candidate is missing from PIPELINE.',evidenceRefs:[],recommendedAction:'Reproject from the authoritative Registry with PipelineAdmissionPolicy.',autoRecoverable:false});
  if(pipeline.rankInvariant===false)add({signalType:'PIPELINE_RANK_INVARIANT_FAILED',severity:'ERROR',component:'pipeline-ranking',aggregateType:'PIPELINE',aggregateId:'strong-candidates',summary:'Pipeline physical order and unified ranks diverged.',evidenceRefs:[],recommendedAction:'Recompute the canonical Pipeline ranking.',autoRecoverable:false});
  for(const id of pipeline.duplicateActive||[])add({signalType:'PIPELINE_DUPLICATE_ACTIVE',severity:'ERROR',component:'pipeline-admission',aggregateType:'JOB',aggregateId:id,summary:'A canonical opportunity appears more than once in active Pipeline.',evidenceRefs:[{type:'jobId',id}],recommendedAction:'Project one canonical Registry identity only.',autoRecoverable:false});
  for(const id of pipeline.terminalPresent||[])add({signalType:'PIPELINE_TERMINAL_PRESENT',severity:'ERROR',component:'pipeline-admission',aggregateType:'JOB',aggregateId:id,summary:'A terminal opportunity remains in active Pipeline.',evidenceRefs:[{type:'jobId',id}],recommendedAction:'Reconcile terminal lifecycle from Registry; preserve history outside Pipeline.',autoRecoverable:false});
  for(const id of pipeline.policyContradictions||[])add({signalType:'PIPELINE_POLICY_CONTRADICTION',severity:'ERROR',component:'pipeline-admission',aggregateType:'JOB',aggregateId:id,summary:'Pipeline admission contains contradictory quality state.',evidenceRefs:[{type:'jobId',id}],recommendedAction:'Resolve authoritative eligibility/evaluation state before admission.',autoRecoverable:false});
  if(today.outcome==='BLOCKED')add({signalType:'TODAY_REFILL_BLOCKED',severity:'ERROR',component:'today-admission',aggregateType:'TODAY',aggregateId:'working-set',summary:`TODAY refill is blocked with ${today.vacantSlots||0} vacant slot(s).`,evidenceRefs:(today.blockedCandidates||[]).map(id=>({type:'jobId',id})),recommendedAction:'Inspect the missing authoritative ranking/registry state; do not admit a lower-quality fallback.',autoRecoverable:false});
  if(Number(today.currentCount||0)<Number(today.target||0)&&Number(today.admissibleRemainder||0)>0)add({signalType:'TODAY_ADMISSIBLE_NOT_PROJECTED',severity:'ERROR',component:'today-admission',aggregateType:'TODAY',aggregateId:'working-set',summary:'An admissible candidate remains outside an under-target TODAY working set.',evidenceRefs:[],recommendedAction:'Re-run deterministic reconciliation and inspect projection integrity.',autoRecoverable:false});
  for(const contradiction of today.stateContradictions||[])add({signalType:'TODAY_STATE_CONTRADICTION',severity:'ERROR',component:'today-state',aggregateType:'JOB',aggregateId:contradiction.jobId||'unknown',summary:'A TODAY row has competing current Human instructions.',evidenceRefs:[{type:'jobId',id:contradiction.jobId||'unknown'}],recommendedAction:'Resolve canonical Human-work state without erasing lifecycle history.',autoRecoverable:false});
  if(today.rankInvariant===false)add({signalType:'TODAY_RANK_INVARIANT_FAILED',severity:'ERROR',component:'today-projection',aggregateType:'TODAY',aggregateId:'working-set',summary:'TODAY physical order and displayed rank diverged.',evidenceRefs:[],recommendedAction:'Run bounded reconciliation; do not rebuild the Sheet layout.',autoRecoverable:false});
  return signals;
}
