import { existsSync, readFileSync } from 'fs';
import { execFileSync } from 'child_process';
import os from 'os';
import path from 'path';
import { inspectNotificationProvider } from '../notifications/runtime.mjs';
import { inspectGoogleOAuthConfig, createGoogleOAuthTokenProviderFromEnv } from '../operations/google-oauth.mjs';
import { GoogleSheetsApiAdapter } from '../human-control-plane/sheets-adapter.mjs';
import { selectTodayMembership } from '../human-control-plane/today-membership.mjs';

const LABELS=['com.careerops.daily','com.careerops.browser-research','com.careerops.application-enrichment','com.careerops.application-executor','com.careerops.outreach-executor','com.careerops.command-subscriber','com.careerops.operational-watch'];
const alive=pid=>{try{process.kill(Number(pid),0);return true;}catch(error){return error?.code==='EPERM';}};
const launchState=(label,{exec=execFileSync,uid=process.getuid?.()}={})=>{const plist=path.join(os.homedir(),'Library','LaunchAgents',`${label}.plist`);try{const output=exec('/bin/launchctl',['print',`gui/${uid}/${label}`],{encoding:'utf8'});return{label,plist,plistExists:existsSync(plist),loaded:true,running:/\bstate = running\b/.test(output),lastExitCode:Number(output.match(/last exit code = (-?\d+)/)?.[1]||0),recentRestartCount:Number(output.match(/runs = (\d+)/)?.[1]||0)};}catch{return{label,plist,plistExists:existsSync(plist),loaded:false,running:false,lastExitCode:null,recentRestartCount:0};}};
const lockState=(lockPath,now)=>{if(!existsSync(lockPath))return{path:lockPath,exists:false,stale:false};try{const owner=JSON.parse(readFileSync(lockPath,'utf8')),ageMs=Math.max(0,new Date(now)-new Date(owner.acquiredAt||owner.startedAt||0));return{path:lockPath,exists:true,owner,ageMs,ownerAlive:alive(owner.pid),stale:ageMs>30*60_000&&!alive(owner.pid)};}catch{return{path:lockPath,exists:true,stale:false,invalid:true};}};

export class OperationalProbeCollector {
  constructor({registry,env=process.env,clock=()=>new Date(),exec=execFileSync,fetchImpl=globalThis.fetch}={}){this.registry=registry;this.db=registry.db;this.env=env;this.clock=clock;this.exec=exec;this.fetch=fetchImpl;}
  async collect(){const now=this.clock().toISOString(),startupGraceMs=Math.max(0,Number(this.env.CAREER_OPS_STARTUP_GRACE_MS||120000)),uptimeMs=os.uptime()*1000,startup={uptimeMs,graceMs:startupGraceMs,active:uptimeMs<startupGraceMs,evidence:'system_uptime'};const agents=LABELS.map(label=>launchState(label,{exec:this.exec}));const subscriber=agents.find(x=>x.label==='com.careerops.command-subscriber');
    const commands=this.db.prepare("SELECT command_id,command_type,correlation_id,received_at,started_at,status FROM workflow_commands WHERE status IN ('RECEIVED','PROCESSING')").all().map(x=>({commandId:x.command_id,commandType:x.command_type,correlationId:x.correlation_id,receivedAt:x.received_at,startedAt:x.started_at,status:x.status,terminalEvent:false}));
    const enrichments=this.db.prepare("SELECT id,status,updated_at,claim_expires_at FROM application_enrichment_requests WHERE status IN ('RESEARCHING','EVALUATING','GENERATING_PACKAGE')").all().map(x=>({id:x.id,status:x.status,claimExpiresAt:x.claim_expires_at,correlationId:`enrichment:${x.id}`}));
    const applications=this.db.prepare("SELECT id,job_id,status,current_stage,blocker_json,confirmation_json,started_at,updated_at FROM application_executions WHERE status IN ('EXECUTING','NEEDS_HUMAN')").all().map(x=>{let b={},c={};try{b=JSON.parse(x.blocker_json||'{}');}catch{}try{c=JSON.parse(x.confirmation_json||'{}');}catch{}const lifecycleNotificationExists=Boolean(this.db.prepare("SELECT 1 ok FROM notification_deliveries WHERE notification_type='NEEDS_HUMAN' AND (json_extract(trigger_snapshot_json,'$.applicationId')=? OR json_extract(trigger_snapshot_json,'$.jobId')=?) LIMIT 1").get(x.id,x.job_id));return{id:x.id,status:x.status,stage:x.current_stage,blockerCode:b.code,verificationUnknown:b.code==='VERIFICATION_UNKNOWN'||c.state==='VERIFICATION_UNKNOWN',externalMutationObserved:x.current_stage==='SUBMIT'||Boolean(c.submissionAttempted),startedAt:x.started_at,updatedAt:x.updated_at,lifecycleNotificationExists};});
    const orphanedRuns=this.db.prepare("SELECT id,status,started_at FROM operational_runs WHERE status='RUNNING' AND started_at<datetime(?,'-30 minutes')").all(now).map(x=>({id:x.id,status:x.status,correlationId:x.id}));
    const selectorDrift=this.db.prepare("SELECT source,COUNT(*) consecutive,COUNT(DISTINCT run_id) runs,GROUP_CONCAT(DISTINCT run_id) ids FROM browser_task_telemetry WHERE outcome='SELECTOR_CHANGED' AND finished_at>=datetime(?,'-1 day') GROUP BY source").all(now).map(x=>({source:x.source,consecutive:x.consecutive,runs:x.runs,runIds:String(x.ids||'').split(',').filter(Boolean)}));
    const challengeSpikes=this.db.prepare("SELECT source,COUNT(*) count,GROUP_CONCAT(DISTINCT run_id) ids FROM browser_task_telemetry WHERE outcome IN ('CHALLENGE','CAPTCHA','AUTH_REQUIRED') AND finished_at>=datetime(?,'-1 day') GROUP BY source").all(now).map(x=>({source:x.source,count:x.count,runIds:String(x.ids||'').split(',').filter(Boolean)}));
    const providerFailures=this.db.prepare("SELECT p.provider,COUNT(*) count,GROUP_CONCAT(DISTINCT p.run_id) ids FROM run_provider_results p JOIN runs r ON r.id=p.run_id WHERE p.status='FAILED' AND COALESCE(p.finished_at,r.finished_at,r.started_at)>=datetime(?,'-1 day') GROUP BY p.provider").all(now).map(x=>({provider:x.provider,count:x.count,runIds:String(x.ids||'').split(',').filter(Boolean)}));
    const metrics=this.registry.getNotificationMetrics();const oldest=this.db.prepare("SELECT MIN(created_at) at FROM notification_deliveries WHERE status IN ('PENDING','PROCESSING')").get()?.at;const provider=inspectNotificationProvider({env:this.env});
    const authConfig=inspectGoogleOAuthConfig({env:this.env});let auth={ok:false,code:authConfig.code,mode:authConfig.mode,provider:authConfig.credentialSource,principal:authConfig.principal,subject:authConfig.subject},sheet={ok:false,code:'NOT_PROBED',spreadsheetId:this.env.CAREER_OPS_SHEET_ID};try{const token=createGoogleOAuthTokenProviderFromEnv({env:this.env,fetchImpl:this.fetch,clock:this.clock});await token.getAccessToken({forceRefresh:true});auth={ok:true,mode:authConfig.mode,provider:authConfig.credentialSource,principal:authConfig.principal,subject:authConfig.subject};if(this.env.CAREER_OPS_SHEET_ID){const adapter=new GoogleSheetsApiAdapter({spreadsheetId:this.env.CAREER_OPS_SHEET_ID,tokenProvider:token,fetchImpl:this.fetch});await adapter.request(`${adapter.base}?fields=spreadsheetId`);sheet={ok:true,spreadsheetId:this.env.CAREER_OPS_SHEET_ID};}}catch(error){auth={ok:false,code:error.code||'WORKSPACE_AUTH_FAILED',mode:authConfig.mode,provider:authConfig.credentialSource,principal:authConfig.principal,subject:authConfig.subject};sheet={ok:false,code:error.code||'SHEET_ACCESS_FAILED',spreadsheetId:this.env.CAREER_OPS_SHEET_ID,transient:Boolean(error.transient)};}
    const pubsub={available:false,subscription:this.env.CAREER_OPS_PUBSUB_SUBSCRIPTION,provider:'command_gateway_pull',googleCredentialDependency:false};
    let gateway={ok:true,url:this.env.CAREER_OPS_COMMAND_GATEWAY_URL};if(gateway.url)try{const response=await this.fetch(`${gateway.url.replace(/\/$/,'')}/health`,{signal:AbortSignal.timeout(8000)});gateway.ok=response.ok;}catch{gateway.ok=false;}
    const watchRow=this.db.prepare("SELECT * FROM operational_watch_runs WHERE status!='RUNNING' ORDER BY started_at DESC LIMIT 1").get(),watchAgent=agents.find(x=>x.label==='com.careerops.operational-watch');const watch={required:String(this.env.CAREER_OPS_OPERATIONAL_WATCH_ENABLED).toLowerCase()==='true',ok:watchRow?watchRow.status==='SUCCESS':true,ageMs:watchRow?Math.max(0,new Date(now)-new Date(watchRow.completed_at||watchRow.started_at)):0,errorCode:watchRow?.error_code||null,error:watchRow?.error||null,launchAgent:watchAgent};
    const workerQueues=this.db.prepare("SELECT work_type,COUNT(*) queue_depth,MIN(queued_at) oldest_queued_at FROM worker_work_items WHERE status='QUEUED' GROUP BY work_type").all().map(x=>({workType:x.work_type,queueDepth:x.queue_depth,oldestQueuedAt:x.oldest_queued_at,worker:{ENRICHMENT:'application-enrichment',APPLICATION:'application-executor',OUTREACH:'outreach-executor'}[x.work_type]}));
    const controlPlane=this.registry.getControlPlaneData({candidateScope:'decision'}),membership=selectTodayMembership(controlPlane),memberIds=new Set(membership.memberJobIds);
    const human=new Map(controlPlane.humanState.map(x=>[`${x.entityType}:${x.entityId}:${x.field}`,String(x.value||'').toUpperCase()])),enrichmentByJob=new Map(controlPlane.enrichmentRequests.map(x=>[x.jobId,x])),executionByJob=new Map(controlPlane.applicationExecutions.map(x=>[x.jobId,x]));
    const stateContradictions=[];for(const item of controlPlane.attentionItems||[]){if(item.entityType!=='JOB'||!memberIds.has(item.jobId))continue;const decision=human.get(`JOB:${item.jobId}:human_decision`)||'NO_ACTION',approval=human.get(`JOB:${item.jobId}:application_decision`)||'NO_ACTION',execution=executionByJob.get(item.jobId),enrichment=enrichmentByJob.get(item.jobId),currentActionOverridesHistory=execution?.status==='NEEDS_HUMAN'||(item.attentionType==='APPROVAL_REQUIRED'&&approval==='HOLD'&&execution?.status==='CANCELLED'&&enrichment?.status==='READY_FOR_REVIEW');if((decision==='HOLD'||approval==='HOLD')&&!currentActionOverridesHistory)stateContradictions.push({jobId:item.jobId,attentionType:item.attentionType});}
    const today={...membership.diagnostics,stateContradictions,rankInvariant:true};
    const pipeline={policyVersion:membership.pipeline.policyVersion,registryCount:membership.pipeline.registryCount,admittedCount:membership.pipeline.admitted.length,excludedCount:membership.pipeline.excludedCount,excludedByRule:membership.pipeline.excludedByRule,admissibleNotProjected:0,rankInvariant:true,duplicateActive:[],terminalPresent:[],policyContradictions:[]};
    return{now,startup,subscriber,launchAgents:agents,workerQueues,commands,enrichments,applications,orphanedRuns,auth,sheet,gateway,pubsub,notifications:{providerReady:provider.providerStatus==='READY',pending:metrics.pending,ambiguous:metrics.ambiguous,oldestPendingAgeMs:oldest?Math.max(0,new Date(now)-new Date(oldest)):0},browserLock:lockState(path.resolve(this.env.BROWSER_SESSION_LOCK||this.env.BROWSER_RESEARCH_LOCK||'data/browser/.careerops-session.lock'),now),selectorDrift,challengeSpikes,providerFailures,watch,pipeline,today};
  }
}
