import { randomUUID } from 'crypto';
import { normalizeOperationalSignal, OPERATIONAL_POLICY_VERSION } from './contracts.mjs';

const parse=(value,fallback)=>{try{return JSON.parse(value||'');}catch{return fallback;}};
const rowView=row=>row?{signalId:row.signal_id,signalType:row.signal_type,severity:row.severity,component:row.component,aggregateType:row.aggregate_type,aggregateId:row.aggregate_id,correlationId:row.correlation_id,detectedAt:row.detected_at,firstSeenAt:row.first_seen_at,lastSeenAt:row.last_seen_at,status:row.status,summary:row.summary,evidenceRefs:parse(row.evidence_refs_json,[]),recommendedAction:row.recommended_action,autoRecoverable:Boolean(row.auto_recoverable),safetyClass:row.safety_class,remediationAction:row.remediation_action,policyVersion:row.policy_version,dedupeKey:row.dedupe_key,detectedEventId:row.detected_event_id,observationCount:row.observation_count,flapCount:row.flap_count,resolvedAt:row.resolved_at,resolutionReason:row.resolution_reason}:null;

export class OperationalSignalRepository {
  constructor({registry,clock=()=>new Date()}={}){if(!registry)throw new TypeError('registry is required');this.registry=registry;this.db=registry.db;this.clock=clock;}
  now(){return this.clock().toISOString();}
  get(id){return rowView(this.db.prepare('SELECT * FROM operational_signals WHERE signal_id=?').get(String(id)));}
  getByDedupeKey(key){return rowView(this.db.prepare('SELECT * FROM operational_signals WHERE dedupe_key=?').get(String(key)));}
  list({statuses=[],limit=100}={}){const normalized=statuses.map(x=>String(x).toUpperCase());return this.db.prepare(`SELECT * FROM operational_signals ${normalized.length?`WHERE status IN (${normalized.map(()=>'?').join(',')})`:''} ORDER BY last_seen_at DESC,signal_id LIMIT ?`).all(...normalized,Math.max(1,Math.min(1000,Number(limit)||100))).map(rowView);}
  attempts(signalId){return this.db.prepare('SELECT * FROM operational_recovery_attempts WHERE signal_id=? ORDER BY attempt').all(signalId).map(row=>({attemptId:row.attempt_id,signalId:row.signal_id,action:row.action,attempt:row.attempt,startedAt:row.started_at,completedAt:row.completed_at,result:row.result,verification:parse(row.verification_json,{}),errorCode:row.error_code,error:row.error}));}
  observe(input){const signal=normalizeOperationalSignal(input),at=input.detectedAt?new Date(input.detectedAt).toISOString():this.now();return this.db.transaction(()=>{let current=this.db.prepare('SELECT * FROM operational_signals WHERE dedupe_key=?').get(signal.dedupeKey);if(!current){const id=input.signalId||randomUUID();this.db.prepare(`INSERT INTO operational_signals(signal_id,signal_type,severity,component,aggregate_type,aggregate_id,correlation_id,detected_at,first_seen_at,last_seen_at,status,summary,evidence_refs_json,recommended_action,auto_recoverable,safety_class,remediation_action,policy_version,dedupe_key,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,'OPEN',?,?,?,?,?,?,?,?,?,?)`).run(id,signal.signalType,signal.severity,signal.component,signal.aggregateType,signal.aggregateId,signal.correlationId,at,at,at,signal.summary,JSON.stringify(signal.evidenceRefs),signal.recommendedAction,signal.autoRecoverable?1:0,signal.safetyClass,signal.remediationAction||null,signal.policyVersion,signal.dedupeKey,at,at);const event=this.registry.recordWorkflowEvent({eventType:'OPERATIONAL_SIGNAL_DETECTED',aggregateType:'OPERATIONAL_RUN',aggregateId:id,correlationId:signal.correlationId,causationId:input.causationId||signal.aggregateId,occurredAt:at,source:'system',actorType:'SYSTEM',payload:{signalType:signal.signalType,severity:signal.severity,component:signal.component,status:'OPEN',autoRecoverable:signal.autoRecoverable,safetyClass:signal.safetyClass},metadata:{refs:{operationalSignalId:id,...Object.fromEntries(signal.evidenceRefs.filter(x=>x&&x.type&&x.id).map(x=>[x.type,x.id]))}},dedupeKey:`operational-signal:${signal.dedupeKey}:detected`});this.db.prepare('UPDATE operational_signals SET detected_event_id=? WHERE signal_id=?').run(event.event.event_id,id);current=this.db.prepare('SELECT * FROM operational_signals WHERE signal_id=?').get(id);}else{const reopen=['RECOVERED','CLOSED','SUPPRESSED'].includes(current.status);this.db.prepare(`UPDATE operational_signals SET severity=?,last_seen_at=?,status=?,summary=?,evidence_refs_json=?,recommended_action=?,auto_recoverable=?,safety_class=?,remediation_action=?,observation_count=observation_count+1,flap_count=flap_count+?,resolved_at=?,resolution_reason=NULL,updated_at=? WHERE signal_id=?`).run(signal.severity,at,reopen?'OPEN':current.status,signal.summary,JSON.stringify(signal.evidenceRefs),signal.recommendedAction,signal.autoRecoverable?1:0,signal.safetyClass,signal.remediationAction||null,reopen?1:0,reopen?null:current.resolved_at,at,current.signal_id);current=this.db.prepare('SELECT * FROM operational_signals WHERE signal_id=?').get(current.signal_id);}this.db.prepare(`INSERT OR IGNORE INTO operational_signal_observations(observation_id,signal_id,observed_at,status,evidence_refs_json,summary) VALUES(?,?,?,?,?,?)`).run(randomUUID(),current.signal_id,at,current.status,JSON.stringify(signal.evidenceRefs),signal.summary);return rowView(current);})();}
  closeAbsent(activeDedupeKeys,{at=this.now()}={}){const active=new Set(activeDedupeKeys);const rows=this.db.prepare("SELECT * FROM operational_signals WHERE status IN ('OPEN','RECOVERING','ESCALATED')").all();const closed=[];for(const row of rows){if(active.has(row.dedupe_key))continue;this.db.prepare("UPDATE operational_signals SET status='CLOSED',resolved_at=?,resolution_reason='condition_cleared',updated_at=? WHERE signal_id=?").run(at,at,row.signal_id);closed.push(this.get(row.signal_id));}return closed;}
  startRecovery(signal,action){const prior=this.attempts(signal.signalId).filter(x=>x.action===action).length,attempt=prior+1,at=this.now(),attemptId=randomUUID();this.db.prepare("UPDATE operational_signals SET status='RECOVERING',updated_at=? WHERE signal_id=?").run(at,signal.signalId);this.db.prepare("INSERT INTO operational_recovery_attempts(attempt_id,signal_id,action,attempt,started_at,result) VALUES(?,?,?,?,?,'RUNNING')").run(attemptId,signal.signalId,action,attempt,at);this.registry.recordWorkflowEvent({eventType:'OPERATIONAL_RECOVERY_STARTED',aggregateType:'OPERATIONAL_RUN',aggregateId:signal.signalId,correlationId:signal.correlationId,causationId:signal.detectedEventId||signal.signalId,occurredAt:at,source:'system',actorType:'SYSTEM',payload:{signalType:signal.signalType,action,attempt},metadata:{refs:{operationalSignalId:signal.signalId,recoveryAttemptId:attemptId}},dedupeKey:`operational-signal:${signal.signalId}:recovery:${action}:${attempt}:started`});return{attemptId,attempt,action};}
  finishRecovery(signal,attempt,{success,verification={},errorCode=null,error=null}={}){const at=this.now(),status=success?'RECOVERED':'OPEN',result=success?'SUCCEEDED':'FAILED';this.db.prepare('UPDATE operational_recovery_attempts SET completed_at=?,result=?,verification_json=?,error_code=?,error=? WHERE attempt_id=?').run(at,result,JSON.stringify(verification),errorCode,error?String(error).slice(0,500):null,attempt.attemptId);this.db.prepare('UPDATE operational_signals SET status=?,resolved_at=?,resolution_reason=?,updated_at=? WHERE signal_id=?').run(status,success?at:null,success?'verified_recovery':null,at,signal.signalId);this.registry.recordWorkflowEvent({eventType:success?'OPERATIONAL_RECOVERY_SUCCEEDED':'OPERATIONAL_RECOVERY_FAILED',aggregateType:'OPERATIONAL_RUN',aggregateId:signal.signalId,correlationId:signal.correlationId,causationId:signal.detectedEventId||signal.signalId,occurredAt:at,source:'system',actorType:'SYSTEM',payload:{signalType:signal.signalType,action:attempt.action,attempt:attempt.attempt,status:result,errorCode},metadata:{refs:{operationalSignalId:signal.signalId,recoveryAttemptId:attempt.attemptId}},dedupeKey:`operational-signal:${signal.signalId}:recovery:${attempt.action}:${attempt.attempt}:${result.toLowerCase()}`});return this.get(signal.signalId);}
  escalate(signal,{reason='recovery_not_safe',notificationSuppressed=false}={}){const current=this.get(signal.signalId)||signal;if(current.status==='ESCALATED')return current;const at=this.now(),episode=Number(current.flapCount)||0,incidentGroupId=`${current.dedupeKey}:episode:${episode}`;this.db.prepare("UPDATE operational_signals SET status='ESCALATED',resolved_at=NULL,resolution_reason=?,updated_at=? WHERE signal_id=?").run(reason,at,signal.signalId);this.registry.recordWorkflowEvent({eventType:'OPERATIONAL_ESCALATED',aggregateType:'OPERATIONAL_RUN',aggregateId:signal.signalId,correlationId:signal.correlationId,causationId:signal.detectedEventId||signal.signalId,occurredAt:at,source:'system',actorType:'SYSTEM',payload:{signalType:signal.signalType,severity:signal.severity,component:signal.component,summary:signal.summary,recommendedAction:signal.recommendedAction,notificationSuppressed,incidentGroupId},metadata:{refs:{operationalSignalId:signal.signalId,aggregateId:signal.aggregateId,incidentGroupId}},dedupeKey:`operational-signal:${signal.signalId}:episode:${episode}:escalated`});return this.get(signal.signalId);}
  suppress(signal,reason='not_actionable'){const at=this.now();this.db.prepare("UPDATE operational_signals SET status='SUPPRESSED',resolved_at=?,resolution_reason=?,updated_at=? WHERE signal_id=?").run(at,reason,at,signal.signalId);return this.get(signal.signalId);}
  metrics(){const counts=Object.fromEntries(this.db.prepare('SELECT status,COUNT(*) count FROM operational_signals GROUP BY status').all().map(x=>[x.status,x.count]));const attempts=this.db.prepare("SELECT COUNT(*) count,SUM(result='SUCCEEDED') succeeded,SUM(result='FAILED') failed FROM operational_recovery_attempts").get();const recovered=this.db.prepare("SELECT AVG((julianday(resolved_at)-julianday(detected_at))*86400000.0) ms FROM operational_signals WHERE status='RECOVERED' AND resolved_at IS NOT NULL").get()?.ms||0;const oldest=this.db.prepare("SELECT MIN(first_seen_at) at FROM operational_signals WHERE status IN ('OPEN','RECOVERING','ESCALATED')").get()?.at||null;return{signalsDetected:Object.values(counts).reduce((a,b)=>a+b,0),open:(counts.OPEN||0)+(counts.RECOVERING||0),recovered:counts.RECOVERED||0,escalations:counts.ESCALATED||0,suppressed:counts.SUPPRESSED||0,recoveriesAttempted:attempts.count||0,recoveriesSucceeded:attempts.succeeded||0,recoveriesFailed:attempts.failed||0,meanRecoveryTimeMs:Math.round(recovered),oldestOpenAt:oldest};}
  summary(){const open=this.list({statuses:['OPEN','RECOVERING','ESCALATED'],limit:1000}),last=this.db.prepare("SELECT s.summary,a.completed_at FROM operational_recovery_attempts a JOIN operational_signals s ON s.signal_id=a.signal_id WHERE a.result='SUCCEEDED' ORDER BY a.completed_at DESC LIMIT 1").get();const critical=open.filter(x=>['ERROR','CRITICAL'].includes(x.severity)).length,warn=open.filter(x=>x.severity==='WARN').length;return{overall:critical?'ATTENTION':warn?'DEGRADED':'HEALTHY',openSignals:open.length,errorOrCritical:critical,warnings:warn,recoveredLast24h:this.db.prepare("SELECT COUNT(*) count FROM operational_signals WHERE status='RECOVERED' AND resolved_at>=datetime('now','-1 day')").get().count,escalations:open.filter(x=>x.status==='ESCALATED').length,lastRecovery:last?.summary||'',lastRecoveryAt:last?.completed_at||'',metrics:this.metrics()};}
}

export function readOperationalSummary(db){const exists=db.prepare("SELECT 1 ok FROM sqlite_master WHERE type='table' AND name='operational_signals'").get();if(!exists)return null;return new OperationalSignalRepository({registry:{db,recordWorkflowEvent(){throw new Error('read-only');}}}).summary();}
