import { detectOperationalSignals } from './detectors.mjs';
import { OperationalSignalRepository } from './repository.mjs';
import { OperationalRemediationPolicy } from './policy.mjs';
import { OperationalProbeCollector } from './probes.mjs';
import { OperationalRecoveryActions } from './actions.mjs';
import { drainActionableNotifications } from '../notifications/runtime.mjs';

export class OperationalIntelligenceService {
  constructor({registry,probes=null,actions=null,repository=null,policy=new OperationalRemediationPolicy(),detector=detectOperationalSignals,env=process.env}={}){if(!registry)throw new TypeError('registry is required');this.registry=registry;this.env=env;this.repository=repository||new OperationalSignalRepository({registry,clock:registry.clock});this.probes=probes||new OperationalProbeCollector({registry,env,clock:registry.clock});this.actions=actions||new OperationalRecoveryActions({registry,env});this.policy=policy;this.detector=detector;}
  getOpenSignals(){return this.repository.list({statuses:['OPEN','RECOVERING','ESCALATED'],limit:1000});}
  getRecentRecoveries(){return this.registry.db.prepare("SELECT s.signal_type signalType,s.summary,a.action,a.completed_at completedAt,a.verification_json verification FROM operational_recovery_attempts a JOIN operational_signals s ON s.signal_id=a.signal_id WHERE a.result='SUCCEEDED' ORDER BY a.completed_at DESC LIMIT 25").all().map(x=>({...x,verification:JSON.parse(x.verification||'{}')}));}
  getSystemSummary(){return this.repository.summary();}
  failedAttempts(signal){return this.repository.attempts(signal.signalId).filter(x=>x.action===signal.remediationAction&&x.result==='FAILED').length;}
  async recoverSignal(signalId){const signal=this.repository.get(signalId);if(!signal)throw Object.assign(new Error(`unknown operational signal: ${signalId}`),{code:'SIGNAL_NOT_FOUND'});const decision=this.policy.decide(signal,{attempts:this.failedAttempts(signal)});if(!['AUTO_RECOVER','RETRY_SAFE'].includes(decision.decision))return{status:'POLICY_BLOCKED',signal,decision};const attempt=this.repository.startRecovery(signal,signal.remediationAction);try{const result=await this.actions.execute(signal.remediationAction,signal);return{status:result.success?'RECOVERED':'RECOVERY_FAILED',signal:this.repository.finishRecovery(signal,attempt,{success:Boolean(result.success),verification:result.verification}),attempt,result};}catch(error){return{status:'RECOVERY_FAILED',signal:this.repository.finishRecovery(signal,attempt,{success:false,errorCode:error.code||'RECOVERY_FAILED',error:error.message}),attempt,error:{code:error.code||'RECOVERY_FAILED',message:error.message}};}}
  async scan({recover=true,closeAbsent=true,deliverNotifications=true}={}){const snapshot=await this.probes.collect(),detected=this.detector(snapshot),observed=detected.map(item=>this.repository.observe(item));if(closeAbsent)this.repository.closeAbsent(observed.map(x=>x.dedupeKey));const recoveries=[],escalations=[];
    for(const signal of observed){if(!['OPEN','RECOVERING'].includes(signal.status))continue;const decision=this.policy.decide(signal,{attempts:this.failedAttempts(signal)});if(['DO_NOT_TOUCH','ESCALATE'].includes(decision.decision)){escalations.push(this.repository.escalate(signal,{reason:decision.reason,notificationSuppressed:Boolean(detected.find(x=>x.dedupeKey===signal.dedupeKey)?.notificationSuppressed)}));continue;}if(decision.decision==='SUPPRESS'){this.repository.suppress(signal,decision.reason);continue;}if(!recover)continue;const attempt=this.repository.startRecovery(signal,signal.remediationAction);try{const result=await this.actions.execute(signal.remediationAction,signal),finished=this.repository.finishRecovery(signal,attempt,{success:Boolean(result.success),verification:result.verification});recoveries.push({signal:finished,attempt,result});if(!result.success&&this.failedAttempts(finished)>=this.policy.thresholds.maxRecoveryAttempts)escalations.push(this.repository.escalate(finished,{reason:'RECOVERY_VERIFICATION_FAILED'}));}catch(error){const finished=this.repository.finishRecovery(signal,attempt,{success:false,errorCode:error.code||'RECOVERY_FAILED',error:error.message});recoveries.push({signal:finished,attempt,error:{code:error.code||'RECOVERY_FAILED',message:error.message}});if(this.failedAttempts(finished)>=this.policy.thresholds.maxRecoveryAttempts)escalations.push(this.repository.escalate(finished,{reason:'RECOVERY_ATTEMPTS_EXHAUSTED'}));}}
    let notifications={status:'SKIPPED',processed:0};if(deliverNotifications&&String(this.env.CAREER_OPS_NOTIFICATIONS_ENABLED).toLowerCase()==='true')try{notifications=await drainActionableNotifications({registry:this.registry,env:this.env});}catch(error){notifications={status:'FAILED',processed:0,errorCode:error.code||'NOTIFICATION_DRAIN_FAILED'};}
    return{checkedAt:snapshot.now,startup:snapshot.startup,detected:observed,recoveries,escalations,notifications,summary:this.repository.summary()};}
}
