import 'dotenv/config';
import { existsSync, mkdirSync, openSync, closeSync, unlinkSync, readFileSync, statSync, writeSync } from 'fs';
import path from 'path';
import { randomUUID } from 'crypto';
import { openJobRegistry } from './registry/job-registry.mjs';
import { OperationalIntelligenceService } from './operational-intelligence/service.mjs';
import { OutreachExecutionService } from './application-activation/service.mjs';
import { createProductionOutreachExecutors } from './outreach-execution/production-executors.mjs';
import { ApplicationConfirmationReconciler } from './application-execution/reconciliation.mjs';
import { GmailApplicationConfirmationSource } from './application-execution/gmail-confirmation-source.mjs';
import { CandidateGmailTokenProvider, CandidateGmailTransport, inspectCandidateGmailConfig } from './outreach-execution/gmail-transport.mjs';
import { rankOperationalCandidates } from './automation/operational-loop.mjs';
import { pushCommandStatus } from './operations/command-worker.mjs';

const lockPath=path.resolve(process.env.CAREER_OPS_OPERATIONAL_WATCH_LOCK||'data/.operational-watch.lock');
function acquireWatchLock(){const attempt=()=>{const fd=openSync(lockPath,'wx',0o600);writeSync(fd,String(process.pid));return fd;};try{return attempt();}catch(error){if(error.code!=='EEXIST')throw error;let owner=0,age=0;try{owner=Number(readFileSync(lockPath,'utf8').trim());age=Date.now()-statSync(lockPath).mtimeMs;}catch{}let alive=false;if(Number.isInteger(owner)&&owner>0)try{process.kill(owner,0);alive=true;}catch{}if(alive||(owner<=0&&age<10*60*1000))return null;unlinkSync(lockPath);return attempt();}}
async function reconcileApplications(registry){const reconciler=new ApplicationConfirmationReconciler({registry}),gmailReady=inspectCandidateGmailConfig().status==='READY',gmail=gmailReady?new GmailApplicationConfirmationSource({transport:new CandidateGmailTransport({tokenProvider:new CandidateGmailTokenProvider()})}):null,results=[];for(const execution of registry.listApplicationExecutions().filter(item=>item.status!=='APPLIED'&&item.status!=='CANCELLED')){let evidence=[];if(gmail)try{const row=registry.getJob(execution.jobId);evidence=await gmail.evidenceFor({execution,job:{company:row?.canonical_company,title:row?.canonical_title}});}catch(error){results.push({executionId:execution.id,status:'GMAIL_UNAVAILABLE',errorCode:error.code||'GMAIL_READ_FAILED'});}const result=reconciler.reconcile(execution.id,{evidence});if(result.status==='RECONCILED')results.push({executionId:execution.id,status:result.status,source:result.reconciliation.decisiveEvidence.source});}return results;}
async function refill(registry,runId){if(!registry.getRun(runId))registry.startRun({id:runId,type:'confirmation-reconciliation'});const ranking=await rankOperationalCandidates({registry,discoveryRunId:runId,profilePath:process.env.CAREER_OPS_PROFILE||'config/profile.yml',portalsPath:process.env.CAREER_OPS_PORTALS||'portals.yml',clock:()=>new Date(),limit:100});registry.finishRun(runId,{status:'SUCCESS'});return{active:registry.listActiveCandidates().length,top10:ranking.top10?.length||0};}
async function main(){mkdirSync(path.dirname(lockPath),{recursive:true});const fd=acquireWatchLock();if(fd==null){console.log(JSON.stringify({status:'LOCKED',lockPath}));return;}const registry=openJobRegistry();const runId=randomUUID(),at=registry.now();registry.db.prepare("INSERT INTO operational_watch_runs(run_id,started_at,status) VALUES(?,?,'RUNNING')").run(runId,at);try{const confirmations=await reconcileApplications(registry),changed=confirmations.some(item=>item.status==='RECONCILED'),refilled=changed?await refill(registry,`confirmation-watch-${runId}`):null,projection=changed&&process.env.CAREER_OPS_SHEET_ID?await pushCommandStatus({registry,spreadsheetId:process.env.CAREER_OPS_SHEET_ID}):{noOp:true,metrics:{dataMutations:0,structuralMutations:0}};const result=await new OperationalIntelligenceService({registry}).scan();const outreachService=new OutreachExecutionService({registry,executors:createProductionOutreachExecutors()});const outreach=await outreachService.process({max:5}),responses=await outreachService.checkResponses();registry.db.prepare("UPDATE operational_watch_runs SET completed_at=?,status='SUCCESS',signals_detected=?,recoveries_attempted=?,recoveries_succeeded=?,escalations=? WHERE run_id=?").run(registry.now(),result.detected.length,result.recoveries.length,result.recoveries.filter(x=>x.result?.success).length,result.escalations.length,runId);console.log(JSON.stringify({status:'SUCCESS',runId,...result,confirmations,refilled,projection:{noOp:projection.noOp,metrics:projection.metrics},outreach,responses:responses.length},null,2));}catch(error){registry.db.prepare("UPDATE operational_watch_runs SET completed_at=?,status='FAILED',error_code=?,error=? WHERE run_id=?").run(registry.now(),error.code||'WATCH_FAILED',String(error.message).slice(0,500),runId);throw error;}finally{registry.close();closeSync(fd);if(existsSync(lockPath))unlinkSync(lockPath);}}
main().catch(error=>{console.error(JSON.stringify({status:'FAILED',errorCode:error.code||'WATCH_FAILED',error:error.message}));process.exitCode=1;});
