import test from 'node:test';import assert from'node:assert/strict';import{mkdirSync,mkdtempSync,writeFileSync}from'fs';import os from'os';import path from'path';
import{createApplicationSubmitCapability,assertApplicationSubmitCapability}from'../application-execution/browser-capability.mjs';import{AtsChromeApplicationAdapter}from'../application-execution/ats-chrome-adapter.mjs';
import{ApplicationExecutionWorker}from'../application-execution/worker.mjs';
import{answerForField}from'../application-execution/canonical-answers.mjs';
const NOW='2026-08-27T01:00:00.000Z';
function authorization(url='https://boards.greenhouse.io/acme/jobs/123'){const plan={status:'READY',planHash:'plan-hash',packageId:'pkg',packageVersion:2,primaryTarget:url};return{id:'auth-1',jobId:'job-1',status:'APPROVED_TO_APPLY',executionPlan:plan};}
function chromeRoot(){const root=mkdtempSync(path.join(os.tmpdir(),'career-ops-app-browser-'));mkdirSync(path.join(root,'Default'));writeFileSync(path.join(root,'Local State'),JSON.stringify({profile:{info_cache:{Default:{name:'Jorge'}}}}));return root;}
function fixture({inspectUrl='https://boards.greenhouse.io/acme/jobs/123',fields=[],challenge=false,confirm=true,confirmAfter=0,confirmText='Application submitted',fillComplete=true}={}){const calls={opened:[],scripts:[],uploads:[],released:0};const inspection={url:inspectUrl,title:'Apply',challenge,fields,submitAvailable:true,bodySample:''};let inspectCalls=0,evidenceCalls=0;const confirmationUrl='https://boards.greenhouse.io/acme/confirmation/123';const driver={async openTab(_w,url){calls.opened.push(url);return 8;},async readTabMetadata(){return{loading:false,url:confirm&&evidenceCalls>=confirmAfter?confirmationUrl:inspectUrl};},async executeJavaScript(_w,_t,source){calls.scripts.push(source);if(source.includes('const fields=')){inspectCalls++;return JSON.stringify(inspection);}if(source.includes('const items=')){const items=JSON.parse(source.match(/const items=(\[.*?\]);const set=/s)?.[1]||'[]'),total=items.length;return JSON.stringify({filled:fillComplete?total:Math.max(0,total-1),total});}if(source.includes('const b='))return JSON.stringify({clicked:true});if(source.includes('body:(document.body')){evidenceCalls++;const done=confirm&&evidenceCalls>=confirmAfter;return JSON.stringify({url:done?confirmationUrl:inspectUrl,title:done?'Confirmation':'Apply',body:done?confirmText:'Still here'});}return'{}';},async uploadFile(_w,_t,selector,file){calls.uploads.push({selector,file});}};const sessionManager={async acquire(){return{windowId:5};},async release(){calls.released++;}};const env={APPLICATION_BROWSER_PROFILE:'jorge',APPLICATION_BROWSER_MODE:'application_submit',APPLICATION_BROWSER_USER_DATA_DIR:chromeRoot()};return{calls,adapter:new AtsChromeApplicationAdapter({env,driver,sessionManager,answers:{fullName:'Jorge Vera',email:'jorge@example.com'},clock:()=>new Date(NOW),sleepFn:async()=>{}})};}

test('application.submit capability is exact to authorization, package, plan, expiry, and domain',()=>{const auth=authorization(),cap=createApplicationSubmitCapability({authorization:auth,now:new Date(NOW)});assert.equal(assertApplicationSubmitCapability(cap,{authorization:auth,plan:auth.executionPlan,url:auth.executionPlan.primaryTarget,now:new Date(NOW)}),true);assert.throws(()=>assertApplicationSubmitCapability(cap,{authorization:auth,plan:auth.executionPlan,url:'https://evil.example/apply',now:new Date(NOW)}),/domain/);assert.throws(()=>assertApplicationSubmitCapability(cap,{authorization:{...auth,id:'other'},plan:auth.executionPlan,url:auth.executionPlan.primaryTarget,now:new Date(NOW)}),/mismatch/);});
test('paused exact authorization can resume, but failed or cancelled authorization cannot',()=>{const auth=authorization();assert.doesNotThrow(()=>createApplicationSubmitCapability({authorization:{...auth,status:'NEEDS_HUMAN'},now:new Date(NOW)}));for(const status of ['FAILED','CANCELLED'])assert.throws(()=>createApplicationSubmitCapability({authorization:{...auth,status},now:new Date(NOW)}),/exact approved/);});
test('ambiguous verification cannot mint another submit capability',()=>{const auth={...authorization(),status:'NEEDS_HUMAN'};assert.throws(()=>createApplicationSubmitCapability({authorization:auth,execution:{status:'NEEDS_HUMAN',blocker:{code:'VERIFICATION_UNKNOWN'}},now:new Date(NOW)}),/ambiguous application verification/);assert.doesNotThrow(()=>createApplicationSubmitCapability({authorization:auth,execution:{status:'NEEDS_HUMAN',blocker:{code:'NOT_APPLIED_CONFIRMED'}},now:new Date(NOW)}));});
test('worker blocks ambiguous reconciliation before inspection or submit',async()=>{const auth={...authorization(),status:'NEEDS_HUMAN'},execution={id:'execution-1',status:'NEEDS_HUMAN',blocker:{code:'VERIFICATION_UNKNOWN'}};let mutations=0;const registry={getApplicationExecutionAuthorization:()=>auth,getApplicationExecutionByAuthorization:()=>execution};const result=await new ApplicationExecutionWorker({registry,executors:{ATS:{async inspect(){mutations++;},async submit(){mutations++;}}}}).executeNext({authorizationId:auth.id});assert.equal(result.status,'BLOCKED');assert.equal(result.externalMutations,0);assert.equal(mutations,0);});
test('canonical exact Name field uses the persisted full name',()=>{assert.equal(answerForField({label:'Name',name:'Name',type:'text'},{fullName:'Jorge Vera'}).value,'Jorge Vera');});

test('ATS adapter fills canonical fields, uploads only requested PDF artifact, and requires confirmation',async()=>{const f=fixture({fields:[{selector:'#name',name:'name',label:'Full name',type:'text',required:true},{selector:'#resume',name:'resume',label:'Resume',type:'file',required:true}]});const auth=authorization(),execution={id:'execution-1'},request={artifactManifest:{files:{'resume.pdf':{path:'/approved/resume.pdf'}}}};const inspection=await f.adapter.inspect({plan:auth.executionPlan,request,execution,authorization:auth});assert.equal(inspection.fields.every(x=>x.canonicalAnswer),true);const result=await f.adapter.submit({plan:auth.executionPlan,request,execution,authorization:auth});assert.equal(result.confirmed,true);assert.equal(f.calls.uploads.length,1);assert.equal(f.calls.uploads[0].file,'/approved/resume.pdf');assert.equal(f.calls.released,1);});

test('ATS adapter waits for delayed Thanks for applying confirmation',async()=>{const f=fixture({fields:[{selector:'#name',name:'name',label:'Full name',type:'text',required:true}],confirmAfter:3,confirmText:'Thanks for applying'});const auth=authorization(),execution={id:'delayed'},request={artifactManifest:{files:{}}};await f.adapter.inspect({plan:auth.executionPlan,request,execution,authorization:auth});const result=await f.adapter.submit({plan:auth.executionPlan,request,execution,authorization:auth});assert.equal(result.confirmed,true);assert.ok(f.calls.scripts.filter(source=>source.includes('body:(document.body')).length>=3);});

test('ATS adapter never clicks submit when an approved field write is incomplete',async()=>{const f=fixture({fields:[{selector:'#name',name:'name',label:'Full name',type:'text',required:true}],fillComplete:false});const auth=authorization(),execution={id:'incomplete'},request={artifactManifest:{files:{}}};await f.adapter.inspect({plan:auth.executionPlan,request,execution,authorization:auth});const result=await f.adapter.submit({plan:auth.executionPlan,request,execution,authorization:auth});assert.equal(result.confirmed,false);assert.equal(result.blocker.code,'FIELD_WRITE_INCOMPLETE');assert.equal(f.calls.scripts.some(source=>source.includes('const b=')),false);});

test('ATS adapter blocks unknown required fields, challenge pages, redirected domains, and ambiguous confirmation',async()=>{const auth=authorization(),request={artifactManifest:{files:{}}};{const f=fixture({fields:[{selector:'#essay',name:'essay',label:'Why us?',type:'textarea',required:true}]});const inspection=await f.adapter.inspect({plan:auth.executionPlan,request,execution:{id:'u'},authorization:auth});assert.equal(inspection.fields[0].canonicalAnswer,false);await f.adapter.stop({execution:{id:'u'}});assert.equal(f.calls.released,1);}{const f=fixture({challenge:true});const result=await f.adapter.inspect({plan:auth.executionPlan,request,execution:{id:'c'},authorization:auth});assert.equal(result.outcome,'CHALLENGE');assert.equal(f.calls.released,1);}{const f=fixture({inspectUrl:'https://evil.example/apply'});await assert.rejects(()=>f.adapter.inspect({plan:auth.executionPlan,request,execution:{id:'r'},authorization:auth}),/outside authorized domain/);assert.equal(f.calls.released,1);}{const f=fixture({confirm:false});const execution={id:'a'};await f.adapter.inspect({plan:auth.executionPlan,request,execution,authorization:auth});const result=await f.adapter.submit({plan:auth.executionPlan,request,execution,authorization:auth});assert.equal(result.confirmed,false);assert.equal(result.blocker.code,'VERIFICATION_UNKNOWN');}});
