import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'fs';
import { GoogleAccountResolver } from '../application-execution/google-account-resolver.mjs';
import { GmailBrowserSearchAdapter, buildSupabaseConfirmationQuery } from '../application-execution/gmail-search-adapter.mjs';
import { loadIdentityRouting, resolveIdentityForPurpose } from '../operations/identity-routing.mjs';

const JORGE='jorgeaveraf@gmail.com',FUBIFO='fubifo@gmail.com',BRUNOVA='brunova@brunova.mx',NOW='2026-08-27T20:00:00.000Z';
function port({accounts=[],active=FUBIFO,messages=[],state='AUTHENTICATED'}={}){const calls={discover:0,open:[],activate:[],search:[],submit:0};let current=active;return{calls,async discoverGoogleAccounts(){calls.discover++;return{state,accounts};},async openGmailAccount(input){calls.open.push(input);},async activateGoogleAccount(input){calls.activate.push(input);current=input.requestedIdentity;},async readActiveGmailIdentity(){return current;},async searchGmail(input){calls.search.push(input);return messages;}};}

test('resolver finds the exact requested identity among multiple Google accounts',async()=>{const browserPort=port({accounts:[{email:FUBIFO,runtimeRef:'runtime-slot-a',active:true},{email:JORGE,runtimeRef:'runtime-slot-b'},{email:BRUNOVA,runtimeRef:'runtime-slot-c'}]});const result=await new GoogleAccountResolver({browserPort}).resolve(JORGE);assert.equal(result.state,'AUTHENTICATED');assert.equal(result.requestedIdentity,JORGE);assert.equal(result.runtimeRef,'runtime-slot-b');assert.deepEqual(result.accounts.map(x=>x.email),[FUBIFO,JORGE,BRUNOVA]);});

test('runtime slot order changes do not affect email identity resolution',async()=>{let accounts=[{email:JORGE,runtimeRef:'runtime-slot-1'},{email:FUBIFO,runtimeRef:'runtime-slot-2'}];const browserPort={async discoverGoogleAccounts(){return{state:'AUTHENTICATED',accounts};}};const resolver=new GoogleAccountResolver({browserPort});assert.equal((await resolver.resolve(JORGE)).runtimeRef,'runtime-slot-1');accounts=[{email:FUBIFO,runtimeRef:'runtime-slot-1'},{email:BRUNOVA,runtimeRef:'runtime-slot-2'},{email:JORGE,runtimeRef:'runtime-slot-3'}];assert.equal((await resolver.resolve(JORGE)).runtimeRef,'runtime-slot-3');});

test('fubifo or Brunova presence never satisfies the application mailbox',async()=>{for(const email of [FUBIFO,BRUNOVA]){const result=await new GoogleAccountResolver({browserPort:port({accounts:[{email,runtimeRef:'only-slot'}]})}).resolve(JORGE);assert.equal(result.state,'NOT_AUTHENTICATED');assert.equal(result.resolved,false);}});

test('requested account absence and Google challenge fail the exact capability preflight',async()=>{const absent=await new GoogleAccountResolver({browserPort:port({accounts:[]})}).resolve(JORGE);assert.equal(absent.state,'NOT_AUTHENTICATED');const challenged=await new GoogleAccountResolver({browserPort:port({state:'CHALLENGE'})}).resolve(JORGE);assert.equal(challenged.state,'CHALLENGE');});

test('Gmail search switches from the current account and verifies exact mailbox before searching',async()=>{const browserPort=port({active:FUBIFO,accounts:[{email:FUBIFO,runtimeRef:'runtime-a',active:true},{email:JORGE,runtimeRef:'runtime-b'}],messages:[{sender:'Supabase Recruiting <notifications@ashbyhq.com>',subject:'Thanks for applying to Supabase',timestamp:NOW,snippet:'We have received your application for Pre-Sales Solutions Architect.'}]});const resolver=new GoogleAccountResolver({browserPort});const result=await new GmailBrowserSearchAdapter({resolver,browserPort,clock:()=>new Date(NOW)}).searchSupabaseConfirmation({requestedIdentity:JORGE,runId:'reconcile-1'});assert.equal(result.state,'APPLIED_CONFIRMED');assert.equal(result.mailboxIdentity,JORGE);assert.equal(result.evidence.confirmationClassification,'APPLIED_CONFIRMED');assert.ok(result.evidence.evidenceHash);assert.equal(browserPort.calls.activate.length,1);assert.equal(browserPort.calls.search[0].mailboxIdentity,JORGE);assert.equal(browserPort.calls.submit,0);});

test('successful exact-mailbox search with no email never becomes NOT_APPLIED',async()=>{const browserPort=port({active:JORGE,accounts:[{email:JORGE,runtimeRef:'runtime-j',active:true}],messages:[]});const result=await new GmailBrowserSearchAdapter({resolver:new GoogleAccountResolver({browserPort}),browserPort}).searchSupabaseConfirmation({requestedIdentity:JORGE,runId:'reconcile-2'});assert.equal(result.state,'EMAIL_CONFIRMATION_NOT_FOUND');assert.notEqual(result.state,'NOT_APPLIED_CONFIRMED');assert.equal(browserPort.calls.submit,0);});

test('application email read is routed by canonical email and Sheets auth remains browser-independent',()=>{const routing=loadIdentityRouting();assert.deepEqual(resolveIdentityForPurpose(routing,'APPLICATION_EMAIL_READ'),{channel:'APPLICATION_EMAIL',sender:JORGE});const health=readFileSync(new URL('../operations/health.mjs',import.meta.url),'utf8');assert.doesNotMatch(health,/google-account-resolver|GmailBrowserSearchAdapter/);});

test('resolver and search adapter contain no hardcoded Gmail account index',()=>{const source=readFileSync(new URL('../application-execution/google-account-resolver.mjs',import.meta.url),'utf8')+readFileSync(new URL('../application-execution/gmail-search-adapter.mjs',import.meta.url),'utf8');assert.doesNotMatch(source,/\/u\/\d/);assert.match(buildSupabaseConfirmationQuery(),/Supabase OR Ashby/);});
