import test from 'node:test';
import assert from 'node:assert/strict';
import { JobRegistry } from '../registry/job-registry.mjs';
import { NotificationPolicyEngine } from '../notifications/policy.mjs';
import { NotificationOutboxService, NotificationDeliveryWorker } from '../notifications/outbox.mjs';
import { drainApplicationEnrichment } from '../application-enrichment/drain.mjs';
import { detectOperationalSignals } from '../operational-intelligence/detectors.mjs';
import { OperationalSignalRepository } from '../operational-intelligence/repository.mjs';

const NOW=new Date('2026-08-29T18:00:00.000Z');
const preferences={enabled:true,recipient:'operator@example.com',provider:'resend',workflowDigests:true,dailyCompletionSummary:true,events:{NEEDS_HUMAN:true,READY_FOR_REVIEW:true,APPLICATION_CONFIRMED:true,APPLICATION_FAILED:true,COMMAND_FAILED:true,ENRICHMENT_BLOCKED:true,COMMUNITY_NEEDS_HUMAN:true,OPERATIONAL_ESCALATION:true,WORKFLOW_DIGEST:true}};
const create=()=>{const registry=new JobRegistry({dbPath:':memory:',clock:()=>NOW,env:{CAREER_OPS_NOTIFICATIONS_ENABLED:'false'}});const outbox=new NotificationOutboxService({db:registry.db,eventWriter:registry.workflowEvents,preferences,clock:()=>NOW,sheetUrl:'https://docs.google.com/spreadsheets/d/sheet/edit'});return{registry,outbox};};

function enrichment(registry,index,status='READY_FOR_REVIEW',lastErrorCode=null){
  const runId=`fixture-run-${index}`;registry.startRun({id:runId,startedAt:NOW.toISOString()});const observed=registry.recordObservation(runId,{provider:'fixture',externalId:String(index),sourceUrl:`https://jobs.example.test/${index}`,title:`Role ${index}`,company:`Company ${index}`,location:'Remote',description:'Fixture',retrievedAt:NOW.toISOString()});registry.finishRun(runId,{finishedAt:NOW.toISOString()});registry.recordHumanActions({accepted:[{actionKey:`action-${index}`,spreadsheetId:'sheet',tabName:'TODAY',entityType:'JOB',entityId:observed.jobId,field:'human_decision',value:'NEXT_STAGE',observedAt:NOW.toISOString(),user:'operator',sourceHash:`hash-${index}`}],rejected:[]});const request=registry.listEnrichmentRequests({jobId:observed.jobId})[0];registry.db.prepare('UPDATE application_enrichment_requests SET status=?,last_error_code=?,updated_at=? WHERE id=?').run(status,lastErrorCode,NOW.toISOString(),request.id);return request.id;
}

test('an enrichment drain shares one run id and emits one terminal digest request',async()=>{const calls=[],runIds=[],worker={registry:{listEnrichmentRequests:()=>[],notificationOutbox:{enqueueWorkflowDigest:value=>{calls.push(value);return{status:'PENDING'};}}},processNext:async({runId})=>{runIds.push(runId);return runIds.length<=9?{status:'READY_FOR_REVIEW',requestId:`request-${runIds.length}`}:{status:'NO_WORK'};}};const result=await drainApplicationEnrichment({worker,maxItems:10,clock:()=>NOW.getTime()});assert.equal(result.processed,9);assert.equal(new Set(runIds).size,1);assert.match(result.runId,/^enrichment-drain-/);assert.equal(calls.length,1);assert.equal(calls[0].results.length,9);});

test('nine ready items create exactly one idempotent actionable digest',()=>{const{registry,outbox}=create();try{const results=Array.from({length:9},(_,i)=>({requestId:enrichment(registry,i+1),status:'READY_FOR_REVIEW'})),first=outbox.enqueueWorkflowDigest({runId:'enrichment-drain-nine',results}),second=outbox.enqueueWorkflowDigest({runId:'enrichment-drain-nine',results});assert.equal(first.notificationType,'WORKFLOW_DIGEST');assert.equal(second.existing,true);assert.equal(registry.db.prepare("SELECT COUNT(*) count FROM notification_deliveries WHERE notification_type='WORKFLOW_DIGEST'").get().count,1);assert.match(first.subject,/9 requieren tu atención/);assert.match(first.bodyText,/\+ 4 más en TODAY/);assert.equal(outbox.metrics().notificationIntentsGrouped,1);}finally{registry.close();}});

test('mixed nine-item outcomes are counted once and the priority list is bounded',()=>{const{registry,outbox}=create();try{const ready=Array.from({length:4},(_,i)=>enrichment(registry,i+1)),answers=Array.from({length:2},(_,i)=>enrichment(registry,i+5,'BLOCKED')),blocked=enrichment(registry,7,'BLOCKED');const results=[...ready.map(requestId=>({requestId,status:'READY_FOR_REVIEW'})),...answers.map(requestId=>({requestId,status:'ANSWER_REQUIRED'})),{requestId:blocked,status:'BLOCKED'},{requestId:'none-1',status:'CANCELLED'},{requestId:'none-2',status:'CANCELLED'}],delivery=outbox.enqueueWorkflowDigest({runId:'enrichment-drain-mixed',status:'PARTIAL',results});assert.match(delivery.bodyText,/4 READY para revisión/);assert.match(delivery.bodyText,/2 necesitan una respuesta/);assert.match(delivery.bodyText,/1 bloqueadas/);assert.equal(delivery.triggerSnapshot.counts.attention,7);assert.equal(delivery.triggerSnapshot.counts.noAction,2);assert.equal((delivery.bodyText.match(/^- /gm)||[]).length,5);assert.match(delivery.bodyText,/\+ 2 más en TODAY/);assert.equal(outbox.enqueueWorkflowDigest({runId:'enrichment-drain-empty',results:[{requestId:'none',status:'CANCELLED'}]}).status,'NO_ATTENTION');assert.equal(registry.db.prepare('SELECT COUNT(*) count FROM notification_deliveries').get().count,1);}finally{registry.close();}});

test('a critical ambiguity stays immediate alongside one ordinary batch digest',()=>{const{registry,outbox}=create();try{const policy=new NotificationPolicyEngine(),requestId=enrichment(registry,1),event={eventId:'e',eventType:'ENRICHMENT_COMPLETED',refs:{runId:'enrichment-drain-critical'},payload:{}};assert.equal(policy.evaluate({event,domain:{enrichmentReady:true,packageValid:true},preferences}).reason,'captured_by_workflow_digest');const digest=outbox.enqueueWorkflowDigest({runId:'enrichment-drain-critical',results:[{requestId,status:'READY_FOR_REVIEW'}]}),critical=policy.evaluate({event:{...event,eventType:'APPLICATION_VERIFICATION_UNKNOWN',refs:{}},domain:{},preferences});assert.equal(digest.notificationType,'WORKFLOW_DIGEST');assert.deepEqual(critical,{decision:'NOTIFY',notificationType:'NEEDS_HUMAN',priority:'CRITICAL'});}finally{registry.close();}});

test('one Workspace auth root suppresses Sheet and watch derivatives while command receiver remains independent',()=>{const signals=detectOperationalSignals({now:NOW.toISOString(),subscriber:{loaded:true,running:true},launchAgents:[],auth:{ok:false,mode:'workspace_broker',provider:'cloud_run_iam_remote_signing_dwd',code:'DWD_TOKEN_EXCHANGE_FAILED'},sheet:{ok:false,code:'DWD_TOKEN_EXCHANGE_FAILED'},watch:{required:true,ok:false,ageMs:999999},notifications:{providerReady:true}}),auth=signals.find(x=>x.signalType==='WORKSPACE_AUTH_FAILED');assert.deepEqual(signals.map(x=>x.signalType),['WORKSPACE_AUTH_FAILED']);assert.ok(auth.evidenceRefs.some(x=>x.type==='affectedComponent'&&x.id==='google-sheets'));assert.equal(auth.evidenceRefs.some(x=>x.id==='command-subscriber'),false);assert.match(auth.recommendedAction,/Administrador de Brunova/);});

test('incident dedupe is stable within an episode but permits a later distinct episode',()=>{const{registry}=create();try{const repository=new OperationalSignalRepository({registry,clock:()=>NOW}),input=detectOperationalSignals({now:NOW.toISOString(),subscriber:{loaded:true,running:true},launchAgents:[],auth:{ok:false,mode:'workspace_broker',provider:'cloud_run_iam_remote_signing_dwd',code:'DWD_TOKEN_EXCHANGE_FAILED'},notifications:{providerReady:true}}).find(x=>x.signalType==='WORKSPACE_AUTH_FAILED'),first=repository.observe(input);repository.escalate(first);repository.escalate(repository.get(first.signalId));assert.equal(registry.db.prepare("SELECT COUNT(*) count FROM workflow_events WHERE event_type='OPERATIONAL_ESCALATED'").get().count,1);repository.closeAbsent([]);const reopened=repository.observe(input);repository.escalate(reopened);const events=registry.db.prepare("SELECT payload_json FROM workflow_events WHERE event_type='OPERATIONAL_ESCALATED' ORDER BY rowid").all().map(x=>JSON.parse(x.payload_json));assert.equal(events.length,2);assert.notEqual(events[0].incidentGroupId,events[1].incidentGroupId);}finally{registry.close();}});

test('hourly guard defers routine mail and never blocks a critical alert',async()=>{const{registry,outbox}=create();try{const ids=Array.from({length:6},()=>outbox.enqueueDeliveryProbe().id);registry.db.prepare("UPDATE notification_deliveries SET status='SENT',sent_at=? WHERE id IN (?,?,?,?,?)").run(NOW.toISOString(),...ids.slice(0,5));let sends=0;const worker=new NotificationDeliveryWorker({outbox,provider:{sendSummary:async()=>{sends++;return{id:'sent'};}},clock:()=>NOW,env:{CAREER_OPS_NOTIFICATION_HOURLY_LIMIT:'5'}});const deferred=await worker.processOne();assert.equal(deferred.status,'RATE_DEFERRED');assert.equal(sends,0);registry.db.prepare("UPDATE notification_deliveries SET priority='CRITICAL',next_attempt_at=NULL WHERE id=?").run(ids[5]);assert.equal((await worker.processOne()).status,'SENT');assert.equal(sends,1);}finally{registry.close();}});

test('control-plane data exposes digest controls and volume metrics without secrets',()=>{const{registry}=create();try{const data=registry.getControlPlaneData();assert.equal(data.notificationPreferences.workflowDigests,true);assert.ok(Object.hasOwn(data.notificationMetrics,'emailsSentToday'));assert.ok(Object.hasOwn(data.notificationMetrics,'estimatedEmailsAvoided'));}finally{registry.close();}});
