import test from 'node:test';
import assert from 'node:assert/strict';
import { drainApplicationEnrichment } from '../application-enrichment/drain.mjs';
import { wakeApplicationEnrichment } from '../operations/enrichment-wake.mjs';
import { detectOperationalSignals } from '../operational-intelligence/detectors.mjs';
import { OperationalIntelligenceService } from '../operational-intelligence/service.mjs';
import { JobRegistry } from '../registry/job-registry.mjs';

const NOW='2026-08-29T14:00:00.000Z';
const base={now:NOW,startup:{active:true,uptimeMs:30000,graceMs:120000},subscriber:{loaded:true,running:true},launchAgents:[],commands:[],workflowStages:[],enrichments:[],applications:[],orphanedRuns:[],auth:{ok:true},sheet:{ok:true},gateway:{ok:true},pubsub:{available:false},notifications:{providerReady:true,pending:0,ambiguous:0,oldestPendingAgeMs:0},browserLock:{stale:false},selectorDrift:[],challengeSpikes:[],providerFailures:[],watch:{required:false,ok:true,ageMs:0}};
const registry=()=>new JobRegistry({dbPath:':memory:',clock:()=>new Date(NOW),env:{CAREER_OPS_NOTIFICATIONS_ENABLED:'false'}});

test('canonical wake uses launchctl kickstart without killing a running drain',()=>{let call;const result=wakeApplicationEnrichment({uid:501,exec:(file,args)=>{call={file,args};return'';}});assert.equal(result.status,'WAKE_REQUESTED');assert.deepEqual(call.args,['kickstart','gui/501/com.careerops.application-enrichment']);});

test('one invocation drains multiple items up to the configured bound in stable worker order',async()=>{const order=[];const worker={registry:{listEnrichmentRequests:()=>Array.from({length:4})},async processNext(){order.push(order.length);return{status:'READY_FOR_REVIEW',processed:1,requestId:String(order.length)};}};const result=await drainApplicationEnrichment({worker,maxItems:5,maxRuntimeMs:60000,clock:(()=>{let n=0;return()=>n++;})()});assert.equal(result.processed,5);assert.deepEqual(order,[0,1,2,3,4]);});

test('startup subscriber recovery is persisted and does not escalate',async()=>{const r=registry();try{const probes={collect:async()=>({...base,subscriber:{loaded:false,running:false}})},actions={execute:async()=>({success:true,verification:{running:true}})};const result=await new OperationalIntelligenceService({registry:r,probes,actions,env:{}}).scan({deliverNotifications:false});assert.equal(result.recoveries[0].signal.status,'RECOVERED');assert.equal(result.escalations.length,0);}finally{r.close();}});

test('Workspace auth is retried before escalation and duplicate sheet alert is suppressed',()=>{const signals=detectOperationalSignals({...base,auth:{ok:false,code:'DWD_TOKEN_EXCHANGE_FAILED',mode:'workspace_broker',provider:'cloud_run_iam_remote_signing_dwd'},sheet:{ok:false,code:'DWD_TOKEN_EXCHANGE_FAILED'}});assert.deepEqual(signals.map(x=>x.signalType),['WORKSPACE_AUTH_FAILED']);assert.equal(signals[0].remediationAction,'RETRY_GOOGLE_AUTH');assert.ok(signals[0].evidenceRefs.some(x=>x.type==='startupGrace'));});

test('persistent auth recovery escalates only after two failed verified scans',async()=>{const r=registry();try{const probes={collect:async()=>({...base,startup:{active:false},auth:{ok:false,code:'GOOGLE_OAUTH_REFRESH_FAILED'},sheet:{ok:false}})},actions={execute:async()=>({success:false,verification:{attempts:3}})},service=new OperationalIntelligenceService({registry:r,probes,actions,env:{}});const first=await service.scan({deliverNotifications:false});assert.equal(first.escalations.length,0);const second=await service.scan({deliverNotifications:false});assert.equal(second.escalations.length,1);assert.equal(second.escalations[0].status,'ESCALATED');}finally{r.close();}});

test('watcher self-recovers a transient with zero escalation and never asks for log inspection',async()=>{const r=registry();try{const snapshot={...base,startup:{active:false},watch:{required:true,ok:false,ageMs:999999,errorCode:'WATCH_FAILED'},launchAgents:[{label:'com.careerops.operational-watch',plistExists:true,loaded:true,running:false,recentRestartCount:1,lastExitCode:1}]},signals=detectOperationalSignals(snapshot),watch=signals.find(x=>x.signalType==='OPERATIONAL_WATCH_FAILURE');assert.ok(watch);assert.doesNotMatch(watch.recommendedAction,/inspect|log|launchagent/i);const service=new OperationalIntelligenceService({registry:r,probes:{collect:async()=>snapshot},actions:{execute:async()=>({success:true,verification:{loaded:true}})},env:{}}),result=await service.scan({deliverNotifications:false});assert.equal(result.escalations.length,0);assert.ok(result.recoveries.some(x=>x.signal.signalType==='OPERATIONAL_WATCH_FAILURE'&&x.result.success));}finally{r.close();}});

test('persistent watcher root creates one causal escalation episode',async()=>{const r=registry();try{const snapshot={...base,startup:{active:false},watch:{required:true,ok:false,ageMs:999999,errorCode:'WATCH_FAILED'},launchAgents:[{label:'com.careerops.operational-watch',plistExists:true,loaded:true,running:false,recentRestartCount:1,lastExitCode:1}]},service=new OperationalIntelligenceService({registry:r,probes:{collect:async()=>snapshot},actions:{execute:async()=>({success:false,verification:{loaded:false}})},env:{}});await service.scan({deliverNotifications:false});await service.scan({deliverNotifications:false});await service.scan({deliverNotifications:false});assert.equal(r.db.prepare("SELECT COUNT(*) count FROM workflow_events WHERE event_type='OPERATIONAL_ESCALATED' AND json_extract(payload_json,'$.signalType')='OPERATIONAL_WATCH_FAILURE'").get().count,1);}finally{r.close();}});
