import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'fs';
import { buildControlPlaneProjection } from '../human-control-plane/projection.mjs';
import { buildEnrichmentCompletion, isEnrichmentCompletionRecord } from '../application-enrichment/completion.mjs';
import { shortRoleLabel, validateRenderedCoverLetter, validateRenderedResume } from '../application-enrichment/artifact-writer.mjs';
import { renderTextPdf } from '../application-enrichment/text-pdf.mjs';

const NOW='2026-08-27T12:00:00.000Z';
const completion=(contactResearch='NOT_RUN')=>({version:'2.1',jobResearch:'COMPLETE',companyResearch:'PARTIAL',hiringResearch:'NONE_FOUND',contactResearch,applicationPathResearch:'COMPLETE',evidenceCount:4,sourceCount:2,sources:['https://example.test/job','https://example.test/company'],lastEnriched:NOW});
function fixture(){const count=18,jobs=Array.from({length:count},(_,i)=>({job:{id:`job-${i}`,title:`AI Engineer ${i}`,company:`Company ${i}`,location:'Remote',url:`https://example.test/${i}`,source:'fixture',lastSeenAt:NOW},assessment:{eligibilityStatus:'ELIGIBLE',finalPriorityScore:100-i,confidence:'high',result:{candidateFit:{reasons:['Relevant systems work.']}}},evaluation:null,applicationPackage:null}));const snapshot=jobs.map((item,i)=>({jobId:item.job.id,rank:i+1,finalPriorityScore:100-i,eligibilityStatus:'ELIGIBLE',isTop10:i<10}));const humanState=[{entityType:'JOB',entityId:'job-0',field:'human_decision',value:'HOLD'},{entityType:'JOB',entityId:'job-1',field:'human_decision',value:'NEXT_STAGE'},{entityType:'JOB',entityId:'job-2',field:'human_decision',value:'NEXT_STAGE'},{entityType:'JOB',entityId:'job-3',field:'human_decision',value:'NEXT_STAGE'},{entityType:'JOB',entityId:'job-3',field:'application_decision',value:'APPROVE_TO_APPLY'},{entityType:'JOB',entityId:'job-5',field:'human_decision',value:'REJECT'}];const enrichmentRequests=[{jobId:'job-1',status:'PENDING',enrichmentCompletion:{}},{jobId:'job-2',status:'READY_FOR_REVIEW',enrichmentCompletion:completion('NONE_FOUND'),applicationPlan:{primaryPath:'ATS'},artifactManifest:{resumeStatus:'READY',coverLetterStatus:'READY',files:{'resume.pdf':{humanFilename:'Jorge Vera - AI Engineer.pdf'},'cover-letter.pdf':{humanFilename:'Jorge Vera - AI Engineer - Cover Letter.pdf'}}}},{jobId:'job-3',status:'READY_FOR_REVIEW',enrichmentCompletion:completion('NOT_RUN')}];const applicationExecutions=[{jobId:'job-3',status:'NEEDS_HUMAN',blocker:{question:'Passport Country'}},{jobId:'job-4',status:'APPLIED',primaryChannel:'ATS',finishedAt:NOW,confirmation:{id:'confirmed-4'}}];return{jobs,contacts:[],contactResearch:[{id:'contact-2',jobId:'job-2',researchedAt:NOW}],humanState,followUps:[],runs:[],syncState:null,enrichmentRequests,applicationExecutions,candidateSelection:{activeCandidates:snapshot.map(item=>({jobId:item.jobId,state:'ACTIVE',preliminaryScore:item.finalPriorityScore,source:'fixture',updatedAt:NOW})),snapshot,top10:snapshot.slice(0,10),researchNeeds:[]}};}

test('TODAY leads with actionable human attention and keeps curated pursuits bounded',()=>{const tabs=buildControlPlaneProjection(fixture()).tabs;const active=tabs.TODAY.filter(row=>row.Lane==='ATTENTION'),curated=tabs.TODAY.filter(row=>row.Lane==='CURATED');assert.ok(active.some(row=>row['Lifecycle State']==='NEEDS_HUMAN'));const falseReady=tabs.TODAY.find(row=>row['Entity ID']==='job-2');assert.equal(falseReady.Stage,'PREPARING');assert.equal(falseReady.Status,'BLOCKED');assert.ok(active.every(row=>row['Attention Type']));assert.ok(curated.length<=10);assert.deepEqual(tabs.TODAY.map(row=>row.Rank),tabs.TODAY.map((_,index)=>index+1));assert.equal(tabs.TODAY.some(row=>row['Entity ID']==='job-4'),false);assert.equal(tabs.TODAY.some(row=>row['Entity ID']==='job-5'),false);});

test('NEEDS_HUMAN remains in TODAY with the exact blocker and not in APPLICATIONS',()=>{const tabs=buildControlPlaneProjection(fixture()).tabs,row=tabs.TODAY.find(item=>item['Entity ID']==='job-3');assert.equal(row['Execution Status'],'NEEDS_HUMAN');assert.equal(row['Human Blocker'],'Passport Country');assert.match(row['Recommended Action'],/Human Answer/);assert.equal(tabs.APPLICATIONS.some(item=>item['Entity ID']==='job-3'),false);});

test('APPLICATIONS contains only confirmed APPLIED executions',()=>{const tabs=buildControlPlaneProjection(fixture()).tabs;assert.deepEqual(tabs.APPLICATIONS.map(row=>row['Entity ID']),['job-4']);assert.equal(tabs.APPLICATIONS[0]['Application Status'],'APPLIED');assert.equal(tabs.APPLICATIONS[0].Confirmation,'confirmed-4');});

test('contact UX does not promote legacy NONE_FOUND and preserves stable per-contact rows',()=>{const tabs=buildControlPlaneProjection(fixture()).tabs;assert.equal(tabs.CONTACTS.find(row=>row['Job ID']==='job-2')['Contact Status'],'NOT_RUN');assert.equal(tabs.CONTACTS.find(row=>row['Job ID']==='job-1')['Contact Status'],'NOT_RUN');assert.equal(new Set(tabs.CONTACTS.map(row=>row['Entity ID'])).size,tabs.CONTACTS.length);assert.equal(tabs.TODAY.find(row=>row['Entity ID']==='job-2').Contacts,'NOT_RUN');});

test('enrichment completion records normalize dimensions and retain auditable sources',()=>{const record=buildEnrichmentCompletion({report:{descriptionComplete:true,sourcesAttempted:[{taskId:'company-search',sourceType:'PUBLIC_WEB',status:'SUCCESS',url:'https://company.test'}],finishedAt:NOW},evidence:[{normalizedField:'description',sourceUrl:'https://job.test'},{normalizedField:'company_context',sourceUrl:'https://company.test'}],contactResearch:{relationships:[]},applicationPlan:{status:'READY'}});assert.equal(isEnrichmentCompletionRecord(record),true);assert.equal(record.jobResearch,'COMPLETE');assert.equal(record.companyResearch,'COMPLETE');assert.equal(record.contactResearch,'NOT_RUN');assert.equal(record.applicationPathResearch,'COMPLETE');assert.equal(record.sourceCount,2);});

test('resume and cover quality gates reject prohibited legacy patterns',()=>{const cv=readFileSync(new URL('../cv.md',import.meta.url),'utf8');const validPdf=renderTextPdf(cv);assert.equal(validateRenderedResume({markdown:cv,pdf:validPdf}).valid,true);assert.equal(validateRenderedResume({markdown:`${cv}\n## Canonical CV (unchanged source)\n${cv}`,pdf:renderTextPdf(`${cv}\n${cv}`)}).valid,false);const good=`# Jorge Vera\n\n## Cover Letter — AI Engineer at Acme\n\n${'I build reliable AI and data systems for operational teams at Acme. '.repeat(20)}`;assert.equal(validateRenderedCoverLetter({markdown:good,company:'Acme',role:'AI Engineer'}).valid,true);assert.equal(validateRenderedCoverLetter({markdown:'# Jorge Vera\n\nJorge Vera brings evidence-backed experience.',company:'Acme',role:'AI Engineer'}).valid,false);});

test('PDF text layer renders inline markdown as clean human-readable text',()=>{const pdf=renderTextPdf('# Jorge Vera\n\n[LinkedIn](https://linkedin.test/jorge)\n\n**Example AI** | Remote\n\n- Built `RAG` systems.').toString('latin1');assert.match(pdf,/LinkedIn: https:\/\/linkedin\.test\/jorge/);assert.match(pdf,/Example AI \| Remote/);assert.match(pdf,/- Built RAG systems\./);assert.doesNotMatch(pdf,/\*\*|\[LinkedIn\]|`RAG`/);});

test('artifact labels are deterministic, safe, and human-readable',()=>{assert.equal(shortRoleLabel('Pre-Sales Solutions Architect (SA) Leader'),'Solutions Architect');assert.equal(`Jorge Vera - ${shortRoleLabel('Senior Data Engineer (Python)')}.pdf`,'Jorge Vera - Data Engineer.pdf');assert.doesNotMatch(shortRoleLabel('AI Engineer / Platform: Core'),/[/:]/);});
