import assert from 'node:assert/strict';
import test from 'node:test';
import { generateKeyPairSync } from 'node:crypto';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { openJobRegistry } from '../registry/job-registry.mjs';
import { classifyMembershipPage, FacebookMembershipVerifier } from '../facebook/membership-verifier.mjs';
import { FacebookMembershipReconciliationService } from '../facebook/membership-reconciliation.mjs';
import { inspectGoogleOAuthConfig, createGoogleOAuthTokenProviderFromEnv } from '../operations/google-oauth.mjs';
import { runHealthCheck } from '../operations/health.mjs';

const community=()=>({id:'c1',canonicalUrl:'https://www.facebook.com/groups/123/',name:'Grupo',topic:'jobs',visibility:'PRIVATE',membershipState:'JOIN_REQUIRED',memberCount:1,activityScore:1,opportunityScore:1,spamScore:0,qualityScore:80,recommendation:'RECOMMENDED',strategyRevision:'r1',candidateKbHash:'kb1',evidence:[]});
function clickedFixture(){const registry=openJobRegistry({dbPath:':memory:'});registry.recordFacebookCommunities([community()]);registry.recordHumanActions({accepted:[{actionKey:'want',spreadsheetId:'s',tabName:'COMMUNITIES',entityType:'COMMUNITY',entityId:'c1',field:'membership_decision',value:'WANT_TO_JOIN',observedAt:'2026-08-25T12:00:00Z',user:'j',sourceHash:'h'}]});const item=registry.listFacebookCommunityJoinPlan()[0];const claim=registry.beginFacebookCommunityJoin({communityId:'c1',authorizationActionId:item.authorization.actionId,authorizedUrl:item.authorization.url,authorizedAt:item.authorization.authorizedAt});registry.recordFacebookCommunityJoinOutcome(claim.execution.id,{outcome:'JOIN_FAILED',clicked:true,reason:'positive_failure_evidence:legacy_fixture',evidence:{}});return registry;}

test('localized membership fixtures classify Spanish and English membership and pending request',()=>{
  assert.equal(classifyMembershipPage({joined:true,labels:['Eres miembro']}).finalState,'JOINED_CONFIRMED');
  assert.equal(classifyMembershipPage({joined:true,labels:['Joined']}).finalState,'JOINED_CONFIRMED');
  assert.equal(classifyMembershipPage({joined:true,labels:['Member']}).finalState,'JOINED_CONFIRMED');
  assert.equal(classifyMembershipPage({pending:true,labels:['Solicitud enviada']}).finalState,'JOIN_REQUESTED');
  assert.equal(classifyMembershipPage({}).finalState,'VERIFICATION_UNKNOWN');
});

test('groups/joins fallback confirms membership by canonical identity and never clicks',async()=>{
  const scripts=[];const managedAdapter={session:{windowId:1},async withOwnedTab(url,work){return work({domAvailable:true,tabId:url.includes('/joins')?3:2,driver:{async executeJavaScript(_w,tab,script){scripts.push(script);if(tab===3)return JSON.stringify({url:'https://www.facebook.com/groups/joins/',title:'Groups',groups:[{url:'https://facebook.com/groups/123/?ref=bookmarks',name:'Grupo'}],body:''});return JSON.stringify({url:'https://www.facebook.com/groups/123/',title:'Grupo',labels:[],joined:false,pending:false,joinVisible:false,needsHuman:false,login:false,challenge:false,body:''});}}});}};
  const result=await new FacebookMembershipVerifier({managedAdapter,sleep:async()=>{}}).verify({authorization:{canonicalUrl:'https://www.facebook.com/groups/123/'}});
  assert.equal(result.finalState,'JOINED_CONFIRMED');assert.equal(result.reason,'membership_matched_in_groups_joins');assert.equal(scripts.some(script=>/\.click\s*\(/.test(script)),false);
});

test('false JOIN_FAILED is corrected once and reconciliation creates no click or duplicate lifecycle action',async()=>{
  const registry=clickedFixture();try{let calls=0;const verifier={async verify(){calls++;return{finalState:'JOINED_CONFIRMED',reason:'membership_signal_visible',evidence:[{membershipLabels:['Eres miembro']}]};}};const service=new FacebookMembershipReconciliationService({registry,verifier});const before=registry.getFacebookCommunityEvents('c1').length;const first=await service.reconcile();const afterFirst=registry.getFacebookCommunityEvents('c1').length;const second=await service.reconcile();const afterSecond=registry.getFacebookCommunityEvents('c1').length;assert.equal(first.newJoinClicks,0);assert.equal(first.results[0].lifecycleCorrected,true);assert.equal(registry.getFacebookCommunity('c1').membershipState,'JOINED_CONFIRMED');assert.equal(afterFirst,before+1);assert.equal(afterSecond,afterFirst);assert.equal(registry.getFacebookCommunityJoinExecutions()[0].clickCount,1);assert.equal(second.newJoinClicks,0);assert.equal(calls,2);}finally{registry.close();}
});

test('JOIN_FAILED requires positive evidence and unknown remains VERIFICATION_UNKNOWN',()=>{const registry=clickedFixture();try{const execution=registry.getFacebookCommunityJoinExecutions()[0];assert.equal(execution.outcome,'JOIN_FAILED');const second=openJobRegistry({dbPath:':memory:'});try{second.recordFacebookCommunities([community()]);second.recordHumanActions({accepted:[{actionKey:'w2',spreadsheetId:'s',tabName:'COMMUNITIES',entityType:'COMMUNITY',entityId:'c1',field:'membership_decision',value:'WANT_TO_JOIN',observedAt:'2026-08-25T12:00:00Z',user:'j',sourceHash:'h2'}]});const item=second.listFacebookCommunityJoinPlan()[0];const claim=second.beginFacebookCommunityJoin({communityId:'c1',authorizationActionId:item.authorization.actionId,authorizedUrl:item.authorization.url,authorizedAt:item.authorization.authorizedAt});assert.throws(()=>second.recordFacebookCommunityJoinOutcome(claim.execution.id,{outcome:'JOIN_FAILED',reason:'no confirmation'}),/positive failure evidence/);second.recordFacebookCommunityJoinOutcome(claim.execution.id,{outcome:'VERIFICATION_UNKNOWN',reason:'no confirmation'});assert.equal(second.getFacebookCommunity('c1').membershipState,'VERIFICATION_UNKNOWN');}finally{second.close();}}finally{registry.close();}});

function machineFixture(){const root=mkdtempSync(path.join(os.tmpdir(),'career-machine-'));const {privateKey}=generateKeyPairSync('rsa',{modulusLength:2048});const credentialsPath=path.join(root,'machine.json');writeFileSync(credentialsPath,JSON.stringify({type:'service_account',client_email:'career-ops@project.iam.gserviceaccount.com',private_key:privateKey.export({type:'pkcs8',format:'pem'}),token_uri:'https://oauth2.googleapis.com/token'}),{mode:0o600});return{root,credentialsPath,env:{GOOGLE_SHEETS_AUTH_MODE:'service_account_impersonation',GOOGLE_MACHINE_CREDENTIALS_FILE:credentialsPath,GOOGLE_IMPERSONATION_SUBJECT:'brunova@brunova.mx',GOOGLE_SHEETS_SCOPES:'https://www.googleapis.com/auth/spreadsheets',GOOGLE_APPLICATION_CREDENTIALS:path.join(root,'broken-unused-adc.json')}};}

test('machine credential impersonation is preferred over broken unused Desktop OAuth fallback',async()=>{const fixture=machineFixture();const inspection=inspectGoogleOAuthConfig({env:fixture.env});assert.equal(inspection.ok,true);assert.equal(inspection.credentialSource,'service_account_json');assert.equal(inspection.subject,'brunova@brunova.mx');const provider=createGoogleOAuthTokenProviderFromEnv({env:fixture.env,fetchImpl:async()=>({ok:true,status:200,json:async()=>({access_token:'machine-token',expires_in:3600})})});assert.equal(await provider.getAccessToken(),'machine-token');assert.equal(provider.toJSON().type,'GoogleServiceAccountImpersonationTokenProvider');});

test('health ignores broken unused OAuth fallback but fails the actually configured provider',async()=>{const fixture=machineFixture();for(const file of ['cv.md','portals.yml'])writeFileSync(path.join(fixture.root,file),'x');mkdirSync(path.join(fixture.root,'config'));mkdirSync(path.join(fixture.root,'candidate'));writeFileSync(path.join(fixture.root,'config/profile.yml'),'x');writeFileSync(path.join(fixture.root,'candidate/manifest.yml'),'x');const dbPath=path.join(fixture.root,'career.db');openJobRegistry({dbPath}).close();const common={projectRoot:fixture.root,dbPath,minimumFreeMb:0,statfs:()=>({bavail:1,bsize:1}),browserWindowDriver:{async listWindowIds(){return[];}},fetchImpl:async()=>({ok:true,status:200,json:async()=>({spreadsheetId:'s'})})};const healthy=await runHealthCheck({...common,env:{...fixture.env,CAREER_OPS_SHEET_ID:'s',BROWSER_MODE:'research_only',BROWSER_PROFILE:'jorge',BROWSER_USER_DATA_DIR:fixture.root},tokenProvider:{async getAccessToken(){return'machine';}}});assert.equal(healthy.checks.find(x=>x.name==='Workspace Auth').status,'OK');const broken=await runHealthCheck({...common,env:{...fixture.env,GOOGLE_SHEETS_AUTH_MODE:'application_default',GOOGLE_APPLICATION_CREDENTIALS:path.join(fixture.root,'missing.json'),CAREER_OPS_SHEET_ID:'s',BROWSER_MODE:'research_only',BROWSER_PROFILE:'jorge',BROWSER_USER_DATA_DIR:fixture.root}});assert.equal(broken.checks.find(x=>x.name==='Workspace Auth').status,'FAIL');});
