import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'crypto';
import { JobRegistry } from '../registry/job-registry.mjs';
import { WorkflowCommandWorker } from '../operations/command-worker.mjs';
import { commandPayloadHash } from '../operations/command-contract.mjs';
import { WorkflowTimelineService } from '../workflow-events/timeline.mjs';
import { WORKFLOW_EVENT_VERSION } from '../workflow-events/contracts.mjs';

const NOW='2026-08-27T20:00:00.000Z';
const registry=()=>new JobRegistry({dbPath:':memory:',clock:()=>new Date(NOW),env:{}});
const base=(overrides={})=>({eventType:'JOB_HELD',aggregateType:'JOB',aggregateId:'job-1',correlationId:'correlation-1',source:'sheet',actorType:'HUMAN',payload:{status:'HOLD'},...overrides});

function addActiveJob(r,suffix='1'){
  const runId=`run-${suffix}`;r.startRun({id:runId});const observed=r.recordObservation(runId,{provider:'fixture',externalId:suffix,sourceUrl:`https://example.test/${suffix}`,title:'AI Engineer',company:'Example',location:'Remote Mexico',description:'Build reliable AI systems.',retrievedAt:NOW});
  r.recordCandidateSelection(runId,{rulesVersion:'fixture',policyHash:'fixture',capacity:10,threshold:0,counts:{raw:1,PASS:1,REJECT:0,UNKNOWN:0,active:1},decisions:[{jobId:observed.jobId,observationId:observed.observationId,outcome:'PASS',preliminaryScore:90,freshnessDays:0,source:'fixture',sourceKey:'fixture',reasons:[],evidenceRefs:[],poolOnly:false,evidenceWeak:false}],activeCandidates:[{jobId:observed.jobId,observationId:observed.observationId,state:'ACTIVE',stateReason:'fixture',preliminaryScore:90,freshnessDays:0,source:'fixture',sourceKey:'fixture',previousRank:null,selectionRank:1}],transitions:[]});r.finishRun(runId);return observed.jobId;
}
const action=(jobId,value,key=value)=>({actionKey:`${jobId}:${key}`,spreadsheetId:'sheet',tabName:'TODAY',entityType:'JOB',entityId:jobId,field:'human_decision',value,observedAt:NOW,user:'jorge',sourceHash:`hash-${key}`});

test('canonical contract accepts a valid compact event and records 3B.1 plus payload hash',()=>{const r=registry();try{const out=r.recordWorkflowEvent(base());assert.equal(out.duplicate,false);const row=r.db.prepare('SELECT * FROM workflow_events').get();assert.equal(row.event_version,WORKFLOW_EVENT_VERSION);assert.match(row.payload_hash,/^[a-f0-9]{64}$/);}finally{r.close();}});
test('contract rejects unknown event/aggregate, missing correlation, arrays, and oversized payloads',()=>{const r=registry();try{assert.throws(()=>r.recordWorkflowEvent(base({eventType:'UPDATED'})),/unknown workflow event type/);assert.throws(()=>r.recordWorkflowEvent(base({aggregateType:'WHATEVER'})),/unknown workflow aggregate/);assert.throws(()=>r.recordWorkflowEvent(base({correlationId:''})),/correlationId is required/);assert.throws(()=>r.recordWorkflowEvent(base({payload:[]})),/payload must be an object/);assert.throws(()=>r.recordWorkflowEvent(base({payload:{values:Array(100).fill('x'.repeat(1000))}})),/16 KiB/);}finally{r.close();}});
test('events are immutable at the database boundary',()=>{const r=registry();try{const id=r.recordWorkflowEvent(base()).event.event_id;assert.throws(()=>r.db.prepare('UPDATE workflow_events SET source=? WHERE event_id=?').run('system',id),/immutable/);assert.throws(()=>r.db.prepare('DELETE FROM workflow_events WHERE event_id=?').run(id),/immutable/);}finally{r.close();}});
test('deterministic dedupe avoids retries but does not collapse independent events',()=>{const r=registry();try{assert.equal(r.recordWorkflowEvent(base({dedupeKey:'transition-1'})).duplicate,false);assert.equal(r.recordWorkflowEvent(base({dedupeKey:'transition-1'})).duplicate,true);r.recordWorkflowEvent(base({eventId:randomUUID()}));assert.equal(r.db.prepare('SELECT COUNT(*) count FROM workflow_events').get().count,2);assert.equal(r.getWorkflowEventMetrics().duplicatesAvoided,1);}finally{r.close();}});
test('command and domain events preserve one correlation and explicit causation',async()=>{const r=registry();try{const envelope={command_version:'3A.1',command_id:randomUUID(),command_type:'jobs.sync',requested_at:NOW,source:'google_sheet',sheet_id:'sheet',requested_by:'jorge',correlation_id:randomUUID(),payload:{}};r.receiveWorkflowCommand({envelope,payloadHash:commandPayloadHash(envelope)});const worker=new WorkflowCommandWorker({registry:r,projectStatus:null,logger:{info(){},error(){}},dispatch:async command=>{r.recordWorkflowEvent({eventType:'JOB_HELD',aggregateType:'JOB',aggregateId:'job-domain',source:'sheet',actorType:'HUMAN',payload:{status:'HOLD'},dedupeKey:`fixture:${command.commandId}`});return{summary:{rejected:0,held:1,enrichmentQueued:0,executed:0}};}});await worker.process(envelope.command_id);const rows=new WorkflowTimelineService({db:r.db}).getByCorrelation(envelope.correlation_id);assert.deepEqual(rows.map(x=>x.eventType),['COMMAND_RECEIVED','COMMAND_STARTED','JOB_HELD','COMMAND_COMPLETED']);assert.ok(rows.every(x=>x.correlationId===envelope.correlation_id));assert.equal(rows[2].causationId,rows[1].eventId);}finally{r.close();}});
test('human decisions emit meaningful events, queue enrichment causally, and NO_ACTION is quiet',()=>{const r=registry();try{const jobId=addActiveJob(r);r.recordHumanActions({accepted:[action(jobId,'NO_ACTION','none')],rejected:[]});assert.equal(r.timeline.getForJob(jobId).length,0);r.recordHumanActions({accepted:[action(jobId,'NEXT_STAGE','next')],rejected:[]});const rows=r.timeline.getForJob(jobId);assert.deepEqual(rows.map(x=>x.eventType),['JOB_NEXT_STAGE_REQUESTED','ENRICHMENT_QUEUED']);assert.equal(rows[1].causationId,rows[0].eventId);const request=r.listEnrichmentRequests({jobId})[0];r.claimNextEnrichmentRequest({runId:'enrich-run',requestId:request.id});r.transitionEnrichmentRequest(request.id,'BLOCKED',{reason:'fixture blocker',runId:'enrich-run'});assert.deepEqual(r.timeline.getForJob(jobId).slice(-2).map(x=>x.eventType),['ENRICHMENT_STARTED','ENRICHMENT_BLOCKED']);}finally{r.close();}});
test('REJECT and HOLD map to their exact canonical events without duplicates on replay',()=>{const r=registry();try{const rejectJob=addActiveJob(r,'reject'),holdJob=addActiveJob(r,'hold');const reject=action(rejectJob,'REJECT','reject'),hold=action(holdJob,'HOLD','hold');r.recordHumanActions({accepted:[reject,hold],rejected:[]});r.recordHumanActions({accepted:[reject,hold],rejected:[]});assert.deepEqual(r.timeline.getForJob(rejectJob).map(x=>x.eventType),['JOB_REJECTED']);assert.deepEqual(r.timeline.getForJob(holdJob).map(x=>x.eventType),['JOB_HELD']);}finally{r.close();}});
test('timeline APIs normalize summaries, stage, refs, chronology, and bounded recent results',()=>{const r=registry();try{r.recordWorkflowEvent(base({eventType:'JOB_NEXT_STAGE_REQUESTED',occurredAt:'2026-08-27T19:00:00Z'}));r.recordWorkflowEvent(base({eventType:'APPLICATION_VERIFICATION_UNKNOWN',aggregateType:'APPLICATION',aggregateId:'app-1',occurredAt:'2026-08-27T21:00:00Z',source:'application_execution',actorType:'SYSTEM',metadata:{refs:{jobId:'job-1',applicationId:'app-1'}}}));const service=new WorkflowTimelineService({db:r.db}),rows=service.getForJob('job-1');assert.equal(rows[0].stage,'DECIDE');assert.equal(rows[0].summary,'Deep preparation requested.');assert.match(rows[1].summary,/could not be verified/);assert.equal(service.getForApplication('app-1').length,1);assert.equal(service.getRecent(1).length,1);}finally{r.close();}});
test('state and event writes roll back together in either failure direction',()=>{const r=registry();try{r.db.exec('CREATE TABLE fixture_state(id TEXT PRIMARY KEY,value TEXT)');assert.throws(()=>r.db.transaction(()=>{r.db.prepare("INSERT INTO fixture_state VALUES('a','changed')").run();r.recordWorkflowEvent(base({eventType:'INVALID'}));})());assert.equal(r.db.prepare('SELECT COUNT(*) count FROM fixture_state').get().count,0);assert.throws(()=>r.db.transaction(()=>{r.recordWorkflowEvent(base({dedupeKey:'rollback-event'}));r.db.prepare("INSERT INTO fixture_state VALUES('b','ok')").run();throw new Error('state failed');})());assert.equal(r.db.prepare("SELECT COUNT(*) count FROM workflow_events WHERE dedupe_key='rollback-event'").get().count,0);}finally{r.close();}});
test('payload sanitizer removes secrets and raw document fields while retaining references',()=>{const r=registry();try{r.recordWorkflowEvent(base({payload:{token:'nope',cookie:'nope',resume:'nope',answerRef:'fact-1'}}));const payload=JSON.parse(r.db.prepare('SELECT payload_json FROM workflow_events').get().payload_json);assert.deepEqual(payload,{answerRef:'fact-1'});}finally{r.close();}});
