import test from 'node:test';
import assert from 'node:assert/strict';
import { JobRegistry } from '../registry/job-registry.mjs';
import { detectOperationalSignals } from '../operational-intelligence/detectors.mjs';
import { OperationalSignalRepository } from '../operational-intelligence/repository.mjs';
import { OperationalRemediationPolicy, assertAllowedRecoveryAction } from '../operational-intelligence/policy.mjs';
import { OperationalIntelligenceService } from '../operational-intelligence/service.mjs';
import { renderOperationalWatchLaunchAgent } from '../operations/launch-agent.mjs';

const NOW='2026-08-28T12:00:00.000Z';
const base={now:NOW,subscriber:{loaded:true,running:true},launchAgents:[],commands:[],workflowStages:[],enrichments:[],applications:[],orphanedRuns:[],auth:{ok:true},sheet:{ok:true},gateway:{ok:true},pubsub:{available:false},notifications:{providerReady:true,pending:0,ambiguous:0,oldestPendingAgeMs:0},browserLock:{stale:false},selectorDrift:[],challengeSpikes:[],providerFailures:[],watch:{required:false,ok:true,ageMs:0}};
const registry=()=>new JobRegistry({dbPath:':memory:',clock:()=>new Date(NOW),env:{CAREER_OPS_NOTIFICATIONS_ENABLED:'false'}});

test('V3E detects stuck command but excludes waiting-for-human workflows',()=>{const signals=detectOperationalSignals({...base,commands:[{commandId:'c1',commandType:'jobs.sync',status:'PROCESSING',startedAt:'2026-08-28T11:00:00Z'}],workflowStages:[{aggregateId:'j1',stage:'APPLY',workflowStatus:'PROCESSING',lastUpdated:'2026-08-28T10:00:00Z',waitingForHuman:true}]});assert.deepEqual(signals.map(x=>x.signalType),['COMMAND_STUCK']);assert.equal(signals[0].remediationAction,'RECOVER_ORPHANED_COMMAND');});
test('V3E never retries ambiguous application submit or forbidden actions',()=>{const [signal]=detectOperationalSignals({...base,applications:[{id:'a1',verificationUnknown:true,lifecycleNotificationExists:true}]});const decision=new OperationalRemediationPolicy().decide(signal);assert.equal(signal.safetyClass,'AMBIGUOUS_EXTERNAL');assert.equal(decision.decision,'DO_NOT_TOUCH');assert.throws(()=>assertAllowedRecoveryAction('RETRY_APPLICATION_SUBMIT'),/policy blocked/);});
test('V3E deduplicates observations and records immutable recovery events',()=>{const r=registry();try{const repo=new OperationalSignalRepository({registry:r,clock:()=>new Date(NOW)}),input={signalType:'SUBSCRIBER_DOWN',severity:'ERROR',component:'command-subscriber',aggregateType:'OPERATIONAL_RUN',aggregateId:'com.careerops.command-subscriber',correlationId:'op',summary:'down',recommendedAction:'restart',autoRecoverable:true,safetyClass:'INTERNAL_ONLY',remediationAction:'RESTART_COMMAND_SUBSCRIBER'};const first=repo.observe(input),second=repo.observe(input);assert.equal(first.signalId,second.signalId);assert.equal(second.observationCount,2);const attempt=repo.startRecovery(second,'RESTART_COMMAND_SUBSCRIBER');repo.finishRecovery(second,attempt,{success:true,verification:{running:true}});assert.equal(repo.get(first.signalId).status,'RECOVERED');assert.deepEqual(r.db.prepare("SELECT event_type FROM workflow_events WHERE aggregate_id=? ORDER BY occurred_at,rowid").all(first.signalId).map(x=>x.event_type),['OPERATIONAL_SIGNAL_DETECTED','OPERATIONAL_RECOVERY_STARTED','OPERATIONAL_RECOVERY_SUCCEEDED']);}finally{r.close();}});
test('V3E service bounds and verifies injected subscriber recovery',async()=>{const r=registry();try{const probes={async collect(){return{...base,subscriber:{loaded:false,running:false}};}},actions={async execute(action){assert.equal(action,'RESTART_COMMAND_SUBSCRIBER');return{success:true,verification:{running:true}};}};const result=await new OperationalIntelligenceService({registry:r,probes,actions,env:{}}).scan({deliverNotifications:false});assert.equal(result.recoveries.length,1);assert.equal(result.recoveries[0].signal.status,'RECOVERED');}finally{r.close();}});
test('V3E detects only dead expired browser locks and repeated source drift',()=>{assert.equal(detectOperationalSignals({...base,browserLock:{stale:false}}).length,0);const signals=detectOperationalSignals({...base,browserLock:{stale:true,path:'/tmp/lock'},selectorDrift:[{source:'linkedin',consecutive:3,runs:2,runIds:['r1','r2']}],challengeSpikes:[{source:'indeed',count:3}],providerFailures:[{provider:'api',count:3}]});assert.deepEqual(new Set(signals.map(x=>x.signalType)),new Set(['BROWSER_LOCK_STALE','BROWSER_SELECTOR_DRIFT','BROWSER_CHALLENGE_SPIKE','PROVIDER_FAILURE_SPIKE']));});
test('V3E watcher plist is interval-based and not kept alive',()=>{const xml=renderOperationalWatchLaunchAgent({projectRoot:'/tmp/career-ops',npmPath:'/usr/bin/npm'});assert.match(xml,/com\.careerops\.operational-watch/);assert.match(xml,/<key>StartInterval<\/key><integer>300<\/integer>/);assert.match(xml,/<key>KeepAlive<\/key><false\/>/);});
