import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { CandidateGmailTokenProvider, CandidateGmailTransport, buildRawCandidateEmail } from '../outreach-execution/gmail-transport.mjs';
import { candidateGmailBrowserCommand } from '../outreach-execution/candidate-gmail-browser.mjs';
import { LinkedInOutreachTransport } from '../outreach-execution/linkedin-transport.mjs';
import { nextBusinessDay, scheduleForPlan } from '../outreach-execution/scheduler.mjs';
import { buildApplicationActivationPlan } from '../application-activation/planner.mjs';
import { OutreachExecutionService } from '../application-activation/service.mjs';

const NOW=new Date('2026-08-29T23:00:00.000Z'),JORGE='jorgeaveraf@gmail.com';
const response=(body,status=200)=>({ok:status>=200&&status<300,status,async json(){return body;}});
function gmailFetch({identity=JORGE,send={id:'gmail-message-1',threadId:'gmail-thread-1'},sendStatus=200}={}){const calls=[];return{calls,fetch:async(url,options={})=>{calls.push({url,method:options.method||'GET',body:options.body});if(url.includes('oauth2.googleapis.com'))return response({access_token:'token',expires_in:3600});if(url.endsWith('/profile'))return response({emailAddress:identity,historyId:'h1'});if(url.endsWith('/messages/send'))return response(send,sendStatus);throw new Error(`unexpected URL ${url}`);}};}
function gmailEnv(){return{CANDIDATE_GMAIL_CLIENT_ID:'client',CANDIDATE_GMAIL_CLIENT_SECRET:'secret',CANDIDATE_GMAIL_REFRESH_TOKEN:'refresh'};}

test('candidate Gmail authorization opens the exact Chrome profile named Jorge',()=>{const root=mkdtempSync(path.join(tmpdir(),'career-gmail-profile-'));mkdirSync(path.join(root,'Default'));writeFileSync(path.join(root,'Local State'),JSON.stringify({profile:{info_cache:{Default:{name:'Jorge'},'Profile 2':{name:'Brunova'}}}}));const command=candidateGmailBrowserCommand({APPLICATION_BROWSER_PROFILE:'jorge',APPLICATION_BROWSER_MODE:'application_submit',APPLICATION_BROWSER_USER_DATA_DIR:root});assert.match(command,/--profile-directory='Default'/);assert.doesNotMatch(command,/Profile 2/);});

test('candidate Gmail verifies the exact sender and persists a provider/thread confirmation',async()=>{const f=gmailFetch(),token=new CandidateGmailTokenProvider({env:gmailEnv(),fetchImpl:f.fetch,clock:()=>NOW}),transport=new CandidateGmailTransport({tokenProvider:token,fetchImpl:f.fetch,clock:()=>NOW});const result=await transport.sendOnce({sender:JORGE,plan:{recipient:'recruiter@example.com',subject:'AI role',body:'Evidence-backed message'}});assert.equal(result.confirmed,true);assert.equal(result.messageId,'gmail-message-1');assert.equal(result.threadId,'gmail-thread-1');assert.equal(f.calls.filter(x=>x.url.endsWith('/messages/send')).length,1);const raw=buildRawCandidateEmail({sender:JORGE,recipient:'recruiter@example.com',subject:'AI role',body:'Body'});assert.match(Buffer.from(raw,'base64url').toString(),/From: jorgeaveraf@gmail.com/);assert.throws(()=>buildRawCandidateEmail({sender:'career@brunova.mx',recipient:'r@example.com',subject:'x',body:'x'}),/exactly/);});

test('candidate Gmail fails closed on wrong mailbox and treats uncertain provider failure as ambiguous',async()=>{const wrong=gmailFetch({identity:'fubifo@gmail.com'}),wrongTransport=new CandidateGmailTransport({tokenProvider:new CandidateGmailTokenProvider({env:gmailEnv(),fetchImpl:wrong.fetch}),fetchImpl:wrong.fetch});await assert.rejects(()=>wrongTransport.sendOnce({sender:JORGE,plan:{recipient:'r@example.com',subject:'x',body:'x'}}),/not jorgeaveraf/);assert.equal(wrong.calls.some(x=>x.url.endsWith('/messages/send')),false);const uncertain=gmailFetch({send:{},sendStatus:503}),uncertainTransport=new CandidateGmailTransport({tokenProvider:new CandidateGmailTokenProvider({env:gmailEnv(),fetchImpl:uncertain.fetch}),fetchImpl:uncertain.fetch});await assert.rejects(()=>uncertainTransport.sendOnce({sender:JORGE,plan:{recipient:'r@example.com',subject:'x',body:'x'}}),error=>error.ambiguous===true);});

test('scheduler uses Mexico City business days and after-application gating',()=>{assert.equal(scheduleForPlan({timing:'IMMEDIATELY_AFTER_APPLICATION'},{now:NOW,applicationConfirmed:false}),null);assert.equal(scheduleForPlan({timing:'IMMEDIATELY_AFTER_APPLICATION'},{now:NOW,applicationConfirmed:true}),NOW.toISOString());assert.equal(nextBusinessDay(NOW),'2026-08-31T15:00:00.000Z');});

test('LinkedIn uses one exact profile action, verifies success, and stops on challenge',async()=>{const calls={open:0,send:0,close:0};const port={async openProfile(){calls.open++;},async inspectProfile(){return{url:'https://www.linkedin.com/in/ana',h1:'Ana Recruiter',body:'Ana Recruiter · Talent Acquisition at Example',buttons:[{text:'Message'}]};},async composeAndSend({mode}){calls.send++;assert.equal(mode,'DIRECT_MESSAGE');return{sent:true};},async verifySend(){return{url:'https://www.linkedin.com/messaging/thread/1',body:'Message sent'};},async close(){calls.close++;}};const transport=new LinkedInOutreachTransport({browserPort:port,clock:()=>NOW});const sent=await transport.sendOnce({plan:{publicUrl:'https://www.linkedin.com/in/ana',contactName:'Ana Recruiter',contactTitle:'Talent Acquisition',company:'Example',body:'Specific evidence-backed role message'}});assert.equal(sent.confirmed,true);assert.equal(calls.send,1);assert.equal(calls.close,1);const challenged={...port,async inspectProfile(){return{title:'Security verification',body:'CAPTCHA',buttons:[]};}};const blocked=await new LinkedInOutreachTransport({browserPort:challenged}).sendOnce({plan:{publicUrl:'https://www.linkedin.com/in/ana',contactName:'Ana Recruiter',body:'x'}});assert.equal(blocked.externalActionRequired,true);assert.equal(calls.send,1);});

test('unsupported professional route becomes a surfaced manual recommendation and selects one contact',()=>{const source={providerId:'public',sourceUrl:'https://example.test',retrievedAt:NOW.toISOString()},plan=buildApplicationActivationPlan({job:{id:'job-1',company:'Example',title:'AI Engineer'},evaluation:{id:'eval-1'},applicationPath:{status:'READY',primaryPath:'ATS',url:'https://example.test/apply'},packageRecord:{id:'pkg',packageVersion:1,artifacts:{outreach:[{type:'RECRUITER_MESSAGE',content:'Specific evidence-backed message for the role.',subject:'Role',evidence_refs:['skill.python']}]}},contactIntelligence:{completionStatus:'COMPLETE_WITH_CONTACT',contacts:[{personRef:'a',name:'Ana',role:'Hiring lead',contactType:'OTHER_RELEVANT',confidence:'MEDIUM',otherPublicRoute:'https://x.com/ana',source},{personRef:'b',name:'Bob',role:'Engineer',contactType:'TEAM_MEMBER',confidence:'HIGH',publicProfileUrl:'https://example.test/bob',source}]}});assert.equal(plan.primaryContact.name,'Ana');assert.equal(plan.secondaryContact.name,'Bob');assert.equal(plan.outreachStrategy,'MANUAL_OUTREACH_RECOMMENDED');assert.equal(plan.outreachPlan.channel,'PLATFORM_MESSAGE');assert.equal(plan.authorizationScope.outreach,'NOT_REQUIRED');});

test('exact outreach authorization executes once only after confirmed application',async()=>{const plan={jobId:'job',contactId:'contact',channel:'RECRUITER_EMAIL',timing:'IMMEDIATELY_AFTER_APPLICATION',recipient:'r@example.com',subject:'Role',body:'Grounded',version:'4.3',hash:'hash'},auth={id:'auth',jobId:'job',enrichmentRequestId:'req',outreachPlanHash:'hash',outreachPlan:plan,status:'APPROVED_OUTREACH'};let applied=false,current=null,sends=0;const registry={getOutreachAuthorization:()=>auth,getOutreachExecutionByAuthorization:()=>current,listApplicationExecutions:()=>applied?[{status:'APPLIED'}]:[],getHumanFieldState:()=>[],listEnrichmentRequests:()=>[{id:'req',status:'READY_FOR_REVIEW',applicationPlan:{activation:{outreachPlan:plan}}}],listOutreachExecutions:()=>[],scheduleOutreachAuthorization:(_id,at)=>Object.assign(auth,{scheduledAt:at}),beginOutreachExecution:()=>current={id:'exec',status:'EXECUTING'},finishOutreachExecution:(_id,{status,confirmation={},blocker={}})=>current={...current,status,providerConfirmation:confirmation,blocker}};const service=new OutreachExecutionService({registry,clock:()=>NOW,executors:{RECRUITER_EMAIL:{async sendOnce(){sends++;return{confirmed:true,messageId:'m1'};}}}});assert.equal((await service.execute({authorizationId:'auth'})).status,'WAITING_FOR_APPLICATION');applied=true;assert.equal((await service.execute({authorizationId:'auth'})).status,'SENT');assert.equal((await service.execute({authorizationId:'auth'})).reused,true);assert.equal(sends,1);});
