import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, writeFileSync } from 'fs';
import os from 'os';
import path from 'path';
import { openJobRegistry } from '../registry/job-registry.mjs';
import { GenericBrowserApplicationExecutor, mergeFieldGroupContext } from '../application-execution/generic-browser-executor.mjs';
import { classifySecurityBoundary, describeSemanticFields, semanticMeaning } from '../application-execution/semantic-form.mjs';
import { MacOsKeychainCredentialStore, generateStrongCredential } from '../application-execution/credential-store.mjs';
import { PLATFORM_SIGNUP_EMAIL, PlatformAccountProvisioner } from '../application-execution/account-provisioning.mjs';
import { renderActionableNotification } from '../notifications/templates.mjs';

const NOW = '2026-08-30T20:00:00.000Z';
function chromeRoot() { const root = mkdtempSync(path.join(os.tmpdir(), 'career-ops-v433-')); mkdirSync(path.join(root, 'Default')); writeFileSync(path.join(root, 'Local State'), JSON.stringify({ profile: { info_cache: { Default: { name: 'Jorge' } } } })); return root; }
function authorization() { const executionPlan = { status:'READY', planHash:'v433-plan', packageId:'pkg-1', packageVersion:4, primaryChannel:'PLATFORM', primaryTarget:'https://careers.example/jobs/7', executionMode:'GENERIC_BROWSER' }; return { id:'auth-v433', jobId:'job-v433', status:'APPROVED_TO_APPLY', executionPlan }; }
function browserFixture({ models, evidence = [{ url:'https://careers.example/confirmation/7', title:'Thank you', body:'Application submitted successfully' }] } = {}) {
  const calls = { clicks:0, fills:0, uploads:[], releases:0, models:0, evidence:0 }, sessionManager = { async acquire(){ return { windowId:3 }; }, async release(){ calls.releases++; } };
  const driver = { async openTab(){ return 4; }, async readTabMetadata(){ return { loading:false, url:'https://careers.example/jobs/7' }; }, async uploadFile(_w,_t,s,p){ calls.uploads.push({s,p}); }, async executeJavaScript(_w,_t,source){ if(source.includes('[class*="captcha" i]'))return JSON.stringify({present:false,interactiveCount:0,controls:[]});if(source.startsWith('(()=>{const visible=')){ const model=models[Math.min(calls.models,models.length-1)];calls.models++;return JSON.stringify(model); } if(source.includes('const items=')){ calls.fills++; const items=JSON.parse(source.match(/const items=(\[.*?\]);const result=/s)?.[1]||'[]');return JSON.stringify({total:items.length,filled:items.length,failures:[]}); } if(source.startsWith('(()=>{const e=document.querySelector')){ calls.clicks++; return JSON.stringify({clicked:true}); } if(source.startsWith('(()=>JSON.stringify')){ const item=evidence[Math.min(calls.evidence,evidence.length-1)];calls.evidence++;return JSON.stringify(item); } return '{}'; } };
  const env={APPLICATION_BROWSER_PROFILE:'jorge',APPLICATION_BROWSER_MODE:'application_submit',APPLICATION_BROWSER_USER_DATA_DIR:chromeRoot(),APPLICATION_BROWSER_TRACE:process.env.APPLICATION_BROWSER_TRACE};
  return { calls, executor:new GenericBrowserApplicationExecutor({env,driver,sessionManager,clock:()=>new Date(NOW),sleepFn:async()=>{},answers:{fullName:'Jorge Vera',email:'jorgeaveraf@gmail.com',phone:'+52 1 234 567 8900'},maxSteps:5}) };
}

test('semantic form resolution maps identity, exact package, selects and unknown real facts',()=>{const fields=describeSemanticFields([{label:'First name',type:'text',required:true},{label:'Email address',type:'email',required:true},{label:'Resume / CV',type:'file',required:true},{label:'Expected annual salary in USD',type:'text',required:true}],{candidateAnswers:{fullName:'Jorge Vera',email:'j@example.com'},artifactManifest:{files:{'resume.pdf':{path:'/exact/resume.pdf',hash:'abc'}}}});assert.equal(fields[0].meaning,'candidate.first_name');assert.equal(fields[0].value,'Jorge');assert.equal(fields[2].source,'EXACT_PACKAGE_ARTIFACT');assert.equal(fields[3].resolved,false);assert.equal(semanticMeaning({label:'Are you authorized to work in Mexico?'}),'candidate.work_authorization');});
test('security boundaries are precise and never represented as candidate questions',()=>{assert.equal(classifySecurityBoundary({text:'Please complete the reCAPTCHA',challenge:{present:true,interactive:true,interactiveCount:1,controls:[{role:'checkbox'}]}}),'CAPTCHA_REQUIRED');assert.equal(classifySecurityBoundary({text:'This site is protected by reCAPTCHA',challenge:{present:true}}),null);assert.equal(classifySecurityBoundary({text:'Enter the code from your authenticator app'}),'MFA_REQUIRED');assert.equal(classifySecurityBoundary({text:'Applications are not accepted in your region'}),'PLATFORM_RESTRICTION');});
test('group context replaces radio option labels with the real application question',()=>{const fields=mergeFieldGroupContext([{selector:'[data-career-ops-field="control-1"]',label:'8+ years',name:'python_years',type:'radio',required:true,valuePresent:true,checked:false,options:[]}],[{selector:'[data-career-ops-field="control-1"]',question:'How many years of professional Python development experience do you have?',context:'How many years of professional Python development experience do you have? 8+ years 5–8 years',options:[{value:'8+',label:'8+ years'},{value:'5-8',label:'5–8 years'}],checked:false}]);assert.equal(fields[0].label,'How many years of professional Python development experience do you have?');assert.equal(fields[0].valuePresent,false);assert.equal(fields[0].options.length,2);});
test('credential store uses a protected reference and strong portable generated secrets',()=>{const calls=[],store=new MacOsKeychainCredentialStore({platform:'darwin',exec:(file,args)=>{calls.push({file,args});return args[0]==='find-generic-password'?'secret\n':'';}}),password=generateStrongCredential();assert.ok(password.length>=28);assert.ok(password.length<=32);const ref=store.put({platformKey:'example.com',accountEmail:PLATFORM_SIGNUP_EMAIL,password});assert.match(ref,/^keychain:\/\//);assert.equal(calls.some(x=>x.file==='/usr/bin/security'&&x.args[0]==='add-generic-password'),true);});
test('generic browser executes a semantic multi-step form and clicks final submit exactly once',async()=>{const page1={url:'https://careers.example/jobs/7',title:'Apply',body:'Application',frames:[],fields:[{selector:'[data-career-ops-field="f1"]',label:'Full name',name:'name',type:'text',required:true,options:[]}],next:{selector:'[data-career-ops-field="f2"]',text:'Next'},finalSubmit:null},page2={url:'https://careers.example/jobs/7/step2',title:'Apply',body:'Final step',frames:[],fields:[{selector:'[data-career-ops-field="f3"]',label:'Phone',name:'phone',type:'tel',required:true,options:[]}],next:null,finalSubmit:{selector:'[data-career-ops-field="f4"]',text:'Submit Application',inForm:true}};const f=browserFixture({models:[page1,page2]}),auth=authorization(),execution={id:'exec-v433',status:'EXECUTING'},request={artifactManifest:{files:{}}};const inspection=await f.executor.inspect({plan:auth.executionPlan,request,execution,authorization:auth});assert.equal(inspection.outcome,'READY');const result=await f.executor.submit({plan:auth.executionPlan,request,execution,authorization:auth});assert.equal(result.confirmed,true,JSON.stringify(result));assert.equal(f.calls.clicks,2);assert.equal(f.calls.releases,1);});
test('post-submit ambiguity is terminal and never generates a second click',async()=>{const page={url:'https://careers.example/jobs/7',title:'Apply',body:'Final step',frames:[],fields:[],next:null,finalSubmit:{selector:'[data-career-ops-field="f1"]',text:'Submit Application',inForm:true}},f=browserFixture({models:[page],evidence:[{url:page.url,title:'Apply',body:'Still processing'}]}),auth=authorization(),execution={id:'exec-ambiguous',status:'EXECUTING'},request={artifactManifest:{files:{}}};await f.executor.inspect({plan:auth.executionPlan,request,execution,authorization:auth});const result=await f.executor.submit({plan:auth.executionPlan,request,execution,authorization:auth});assert.equal(result.blocker.code,'VERIFICATION_UNKNOWN');assert.equal(f.calls.clicks,1);});
test('registry persists platform accounts without plaintext passwords',()=>{const registry=openJobRegistry({dbPath:':memory:'});try{assert.equal(registry.getSchemaVersion(),35);const account=registry.upsertPlatformAccount({platformKey:'x.example',accountEmail:PLATFORM_SIGNUP_EMAIL,credentialReference:'keychain://ref'});assert.equal(account.accountEmail,PLATFORM_SIGNUP_EMAIL);assert.equal(JSON.stringify(account).includes('password'),false);}finally{registry.close();}});
test('account provisioning uses fubifo, reuses the protected account, and correlates ordinary verification',async()=>{const registry=openJobRegistry({dbPath:':memory:'}),secrets=new Map(),credentialStore={health:()=>({status:'READY'}),put:({platformKey,accountEmail,password})=>{secrets.set(`${platformKey}:${accountEmail}`,password);return'keychain://fixture';},get:({platformKey,accountEmail})=>secrets.get(`${platformKey}:${accountEmail}`)},calls=[];try{const provisioner=new PlatformAccountProvisioner({registry,credentialStore,verificationReader:{async findVerification(input){calls.push(input);return{verified:true,evidence:{messageId:'verification-1'}};}}});const first=provisioner.prepare({platformKey:'jobs.example',executionId:'exec-1'});assert.equal(first.account.accountEmail,PLATFORM_SIGNUP_EMAIL);assert.equal(first.account.credentialReference,'keychain://fixture');const verification=await provisioner.verify({account:first.account,executionId:'exec-1',requestedAt:NOW,browserContext:{session:{windowId:3}}});assert.equal(verification.status,'VERIFIED');assert.equal(calls[0].executionId,'exec-1');const second=provisioner.prepare({platformKey:'jobs.example',executionId:'exec-2'});assert.equal(second.existing,true);assert.equal(second.password,first.password);}finally{registry.close();}});
test('one application batch renders one consolidated digest',()=>{const rendered=renderActionableNotification('APPLICATION_BATCH_DIGEST',{applied:[{company:'Scalepex'},{company:'Oowlish'}],blocked:[{company:'ChainGPT',action:'Solve CAPTCHA',instruction:'Solve only the CAPTCHA.'}],failed:[],todayPromoted:2,outreach:{sent:1,manual:1}});assert.match(rendered.subject,/1 acción breve/);assert.match(rendered.text,/Scalepex/);assert.match(rendered.text,/Solve CAPTCHA/);assert.doesNotMatch(rendered.text,/CAPTCHA_REQUIRED/);});
