import test from 'node:test';
import assert from 'node:assert/strict';
import {openJobRegistry} from '../registry/job-registry.mjs';
import {WorkerOrchestrator} from '../execution-orchestration/worker-registry.mjs';
import {buildHumanQuestion,validateHumanQuestion} from '../application-execution/human-question.mjs';
import {renderApplicationExecutorLaunchAgent,renderOutreachExecutorLaunchAgent} from '../operations/launch-agent.mjs';
import {deriveHumanAttentionItems} from '../human-attention/service.mjs';
import {runOperationalLoop} from '../automation/operational-loop.mjs';

test('orchestrator persists queue/wake evidence and never force-restarts a running worker',()=>{const registry=openJobRegistry({dbPath:':memory:'});try{registry.upsertWorkerWorkItem({workKey:'application:a1',workType:'APPLICATION',workerName:'application-executor',aggregateType:'APPLICATION',aggregateId:'a1',jobId:null});const calls=[];const orchestrator=new WorkerOrchestrator({registry,exec:(file,args)=>{calls.push(args);if(args[0]==='print')return 'state = running\npid = 42\n';throw new Error('kickstart must not run');}});const result=orchestrator.wake('APPLICATION');assert.equal(result.result,'ALREADY_RUNNING');assert.equal(result.queueDepth,1);assert.equal(registry.getWorkerWorkItem('application:a1').wakeRequestedAt!==null,true);assert.equal(calls.some(args=>args.includes('-k')),false);}finally{registry.close();}});

test('orchestrator reports NO_WORK and structured unavailable failure',()=>{const registry=openJobRegistry({dbPath:':memory:'});try{const orchestrator=new WorkerOrchestrator({registry,exec:()=>{const error=new Error('missing');error.code='ESRCH';throw error;}});assert.equal(orchestrator.wake('APPLICATION').result,'NO_WORK');registry.upsertWorkerWorkItem({workKey:'application:a2',workType:'APPLICATION',workerName:'application-executor',aggregateType:'APPLICATION',aggregateId:'a2'});assert.equal(orchestrator.wake('APPLICATION').result,'FAILED_PERSISTENT');}finally{registry.close();}});

test('human question contract is precise and rejects credential collection',()=>{const question=buildHumanQuestion({jobId:'j1',executionId:'e1',field:{name:'work_authorization',label:'Are you authorized to work in Mexico?',context:'Required eligibility field',allowedValues:['YES','NO']}});assert.equal(question.answer_type,'ENUM');assert.equal(question.sensitive,false);assert.throws(()=>validateHumanQuestion({...question,prompt:'Enter your MFA code'}),/may not be requested/);});

test('technical executor blockers never become ANSWER_REQUIRED',()=>{const items=deriveHumanAttentionItems({jobs:[{job:{id:'j1',company:'C',title:'R'}}],applicationExecutions:[{jobId:'j1',status:'NEEDS_HUMAN',blocker:{code:'EXECUTOR_UNAVAILABLE'},updatedAt:new Date().toISOString()}],workflowStatuses:[],humanState:[]});assert.equal(items.some(x=>x.attentionType==='ANSWER_REQUIRED'),false);});

test('execution workers have immediate wake plus periodic fallback launch agents',()=>{for(const plist of [renderApplicationExecutorLaunchAgent({projectRoot:process.cwd(),npmPath:process.execPath}),renderOutreachExecutorLaunchAgent({projectRoot:process.cwd(),npmPath:process.execPath})]){assert.match(plist,/<key>StartInterval<\/key><integer>60<\/integer>/);assert.match(plist,/<key>RunAtLoad<\/key><true\/>/);assert.doesNotMatch(plist,/KeepAlive<\/key><true/);}});

test('scheduled operations reconcile human input before discovery and project last',async()=>{const registry=openJobRegistry({dbPath:':memory:'}),calls=[];try{const result=await runOperationalLoop({id:'v432-daily',registry,clock:()=>new Date('2026-08-30T16:00:00.000Z'),projectRoot:process.cwd(),spreadsheetId:'sheet',humanInputStage:async()=>{calls.push('reconcile');return{imported:1};},dailyRunner:async({runId})=>{calls.push('discovery');return{status:'SUCCESS',summary:{run:{id:runId},discovery:{observations:0,newJobs:0,changedJobs:0},failures:[]}};},rankStage:async()=>{calls.push('rank');return{processed:0,eligible:0,shortlisted:0,shortlistedJobIds:[],recommendations:[]};},evaluationStage:async()=>({completed:0,apply:0,evaluations:[]}),packageStage:async()=>({ready:0,packages:[]}),sheetStage:async()=>{calls.push('project');return{synced:true,spreadsheetId:'sheet'};},notificationProvider:null});assert.equal(result.status,'SUCCESS');assert.deepEqual(calls,['reconcile','discovery','rank','project']);}finally{registry.close();}});
