import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, writeFileSync } from 'fs';
import os from 'os';
import path from 'path';
import { APPLICATION_CHALLENGE, classifyApplicationChallenge, resolveApplicationChallenge } from '../application-execution/challenge-resolver.mjs';
import { deriveExperienceDuration } from '../application-execution/experience-duration.mjs';
import { QUESTION_RESOLUTION, resolveApplicationQuestions } from '../application-execution/question-resolver.mjs';
import { GenericBrowserApplicationExecutor } from '../application-execution/generic-browser-executor.mjs';
import { openJobRegistry } from '../registry/job-registry.mjs';

const passive = { url:'https://smartapply.indeed.com/apply', body:'Este sitio está protegido por reCAPTCHA', challenge:{present:true,interactiveCount:0,controls:[]}, fields:[], next:null };

test('Indeed reCAPTCHA legal text is passive and bounded waiting continues automatically after seven seconds',async()=>{let elapsed=0,observations=0;const result=await resolveApplicationChallenge({evidence:passive,wait:async ms=>{elapsed+=ms;},waits:[5000,2000,5000],observe:async()=>++observations===1?passive:{...passive,body:'Application questions',challenge:{present:false},fields:[{label:'Summary'}],next:{text:'Continue',disabled:false}}});assert.equal(result.outcome,APPLICATION_CHALLENGE.NONE);assert.equal(result.requiresHuman,false);assert.equal(elapsed,7000);assert.equal(result.progressed,true);});

test('reCAPTCHA footer text on an already interactable Indeed form is immediately NO_CHALLENGE',()=>{const result=classifyApplicationChallenge({...passive,fields:[{label:'Summary',required:true}],next:{text:'Continue',disabled:false}});assert.equal(result.outcome,APPLICATION_CHALLENGE.NONE);assert.equal(result.passiveResolved,true);});

test('an observable checkbox or puzzle is an interactive CAPTCHA and fails closed',()=>{const result=classifyApplicationChallenge({body:'Verify you are human',challenge:{present:true,interactive:true,interactiveCount:1,controls:[{role:'checkbox',label:'I am human'}]}});assert.equal(result.outcome,APPLICATION_CHALLENGE.CAPTCHA);assert.equal(result.requiresHuman,true);});

test('passive timeout is a technical recovery class rather than a CAPTCHA handoff',async()=>{const result=await resolveApplicationChallenge({evidence:passive,wait:async()=>{},waits:[5,5],maxWaitMs:10,observe:async()=>passive});assert.equal(result.outcome,APPLICATION_CHALLENGE.TECHNICAL_TIMEOUT);assert.equal(result.requiresHuman,false);assert.equal(result.reason,'PASSIVE_CHALLENGE_TIMEOUT');});

const candidate={
  fullName:'Jorge Vera',
  language:{english:{proficiency:'C1'}},
  compensation:{byEmploymentType:{contract:{desired:70,currency:'USD',period:'hour'}}},
  professionalSummary:'AI Systems Engineer building production-grade data, backend, automation, and evidence-backed AI systems.',
  skills:[{id:'skill.python',name:'Python',project_refs:['project.ai'],evidence_refs:['claim.ai']}],
  projects:[{id:'project.ai',experience_ref:'exp.ai',technologies:['Python'],capabilities:['AI automation']}],
  experience:[{id:'exp.ai',role:'AI Systems Engineer',start:'2023-08',end:'2026-08',domains:['AI automation'],project_refs:['project.ai'],responsibility_claim_refs:['claim.ai']},{id:'exp.parallel',role:'Concurrent AI consultant',start:'2024-01',end:'2025-01',domains:['AI'],project_refs:['project.ai'],responsibility_claim_refs:['claim.ai']}],
};

test('experience duration merges overlapping evidence and rounds conservatively',()=>{const result=deriveExperienceDuration({subject:'Python',...candidate,asOf:new Date('2026-08-30T00:00:00Z')});assert.equal(result.months,36);assert.equal(result.years,3);assert.equal(result.derivation,'MERGED_CALENDAR_INTERVALS_CONSERVATIVE_FLOOR');});

test('Scalepex questions resolve summary, AI years and English while scoped compensation remains human',()=>{const fields=[{label:'Summary',type:'textarea',required:true},{label:'How many years of experience do you have as an AI Engineer?',type:'number',required:true},{label:'Do you speak fluent English in professional environments?',type:'radio',required:true},{label:'What are your salary expectations under a contractor scheme, in MXN per month?',type:'number',required:true}],result=resolveApplicationQuestions(fields,{candidateAnswers:candidate,now:new Date('2026-08-30T00:00:00Z')});assert.deepEqual(result.fields.map(item=>item.resolutionType),[QUESTION_RESOLUTION.GENERATED,QUESTION_RESOLUTION.DERIVED,QUESTION_RESOLUTION.POLICY,QUESTION_RESOLUTION.HUMAN]);assert.equal(result.metrics.generated,1);assert.equal(result.metrics.derived,1);assert.equal(result.metrics.deterministic,1);assert.equal(result.metrics.human,1);assert.equal(result.metrics.llmCalls,0);});

test('LinkedIn Easy Apply uses the same semantic resolver and resolution policy',()=>{const fields=[{label:'How many years of Python experience do you have?',type:'number',required:true},{label:'Do you speak fluent English professionally?',type:'radio',required:true}],result=resolveApplicationQuestions(fields,{platform:'linkedin',candidateAnswers:candidate,now:new Date('2026-08-30T00:00:00Z')});assert.deepEqual(result.fields.map(item=>item.resolutionType),[QUESTION_RESOLUTION.DERIVED,QUESTION_RESOLUTION.POLICY]);assert.equal(result.metrics.llmCalls,0);});

test('English fluency is not inferred when authoritative proficiency is absent',()=>{const [field]=resolveApplicationQuestions([{label:'Do you speak fluent English in professional environments?',required:true}],{candidateAnswers:{}}).fields;assert.equal(field.resolutionType,QUESTION_RESOLUTION.HUMAN);assert.equal(field.resolved,false);});

test('compensation does not cross contractor hourly USD into contractor monthly MXN',()=>{const [field]=resolveApplicationQuestions([{label:'Monthly contractor compensation expectation in MXN',required:true}],{candidateAnswers:candidate}).fields;assert.equal(field.resolutionType,QUESTION_RESOLUTION.HUMAN);});

test('semantically equivalent prior answer is reused across wording variants',()=>{const memory=[{id:'answer-1',semanticKey:'experience.python.years',answer:3,scope:'GLOBAL',reusable:true,updatedAt:'2026-08-30T00:00:00Z'}];const [field]=resolveApplicationQuestions([{label:'How many years have you used Python professionally?',required:true}],{candidateAnswers:{},answerMemory:memory}).fields;assert.equal(field.resolutionType,QUESTION_RESOLUTION.PREVIOUS);assert.equal(field.value,3);});

test('human bundle minimization leaves only irreducible questions',()=>{const fields=[{label:'Full name',required:true},{label:'Email',required:true},{label:'Summary',required:true},{label:'Python years of experience',required:true},{label:'AI Engineer years of experience',required:true},{label:'Professional English fluency',required:true},{label:'LinkedIn URL',required:true},{label:'Phone',required:true},{label:'AWS Bedrock production experience',required:true},{label:'Monthly contractor compensation expectation in MXN',required:true}],answers={...candidate,email:'j@example.com',phone:'123',linkedin:'https://linkedin.example/j'};const result=resolveApplicationQuestions(fields,{candidateAnswers:answers,now:new Date('2026-08-30T00:00:00Z')});assert.equal(result.fields.filter(item=>!item.resolved).length,2);assert.deepEqual(result.fields.filter(item=>!item.resolved).map(item=>item.semanticKey),['experience.aws_bedrock.years','compensation.contractor.monthly_mxn']);});

function chromeRoot(){const root=mkdtempSync(path.join(os.tmpdir(),'career-ops-v441-'));mkdirSync(path.join(root,'Default'));writeFileSync(path.join(root,'Local State'),JSON.stringify({profile:{info_cache:{Default:{name:'Jorge'}}}}));return root;}

test('executor fills all known fields on a page before pausing for one unknown fact',async()=>{const page={url:'https://careers.example/apply',title:'Questions',body:'Application questions',frames:[],fields:[{selector:'#name',label:'Full name',name:'name',type:'text',required:true,options:[]},{selector:'#unknown',label:'What private preference have you not supplied?',name:'private_preference',type:'text',required:true,options:[]}],finalSubmit:{selector:'#submit',text:'Submit Application',inForm:true}},calls={fills:[]},driver={async openTab(){return 2;},async readTabMetadata(){return{loading:false,url:page.url};},async executeJavaScript(_w,_t,source){if(source.includes('[class*="captcha" i]'))return JSON.stringify({present:false,interactiveCount:0,controls:[]});if(source.startsWith('(()=>{const visible='))return JSON.stringify(page);if(source.includes('const controls='))return'[]';if(source.includes('const items=')){const items=JSON.parse(source.match(/const items=(\[.*?\]);const result=/s)?.[1]||'[]');calls.fills.push(...items);return JSON.stringify({total:items.length,filled:items.length,failures:[]});}return'{}';}},sessionManager={async acquire(){return{windowId:1};},async release(){}};const env={APPLICATION_BROWSER_PROFILE:'jorge',APPLICATION_BROWSER_MODE:'application_submit',APPLICATION_BROWSER_USER_DATA_DIR:chromeRoot(),APPLICATION_PASSIVE_CHALLENGE_WAITS_MS:'0'};const executor=new GenericBrowserApplicationExecutor({env,driver,sessionManager,answers:{fullName:'Jorge Vera'},sleepFn:async()=>{}}),plan={status:'READY',planHash:'plan-441',packageId:'pkg',packageVersion:1,primaryChannel:'PLATFORM',primaryTarget:page.url,executionMode:'GENERIC_BROWSER'},authorization={id:'auth-441',jobId:'job-441',status:'APPROVED_TO_APPLY',executionPlan:plan},execution={id:'exec-441',jobId:'job-441',status:'EXECUTING',mutationState:'PRE_SUBMIT'},request={artifactManifest:{files:{}}};await executor.inspect({plan,request,execution,authorization});const result=await executor.submit({plan,request,execution,authorization});assert.equal(result.reason,'REAL_HUMAN_FACT_REQUIRED');assert.equal(result.blocker.requiredQuestions.length,1);assert.equal(calls.fills.length,1);assert.equal(calls.fills[0].value,'Jorge Vera');});

test('schema 35 installs scoped question answer memory',()=>{const registry=openJobRegistry({dbPath:':memory:'});try{assert.equal(registry.getSchemaVersion(),35);assert.ok(registry.db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='application_question_resolutions'").get());}finally{registry.close();}});
