import test from 'node:test';
import assert from 'node:assert/strict';
import { ApplicationConfirmationReconciler, classifyApplicationReconciliation, collectExecutionConfirmationEvidence, correlateConfirmationEmail } from '../application-execution/reconciliation.mjs';
import { diffMatrices, MemorySheetsAdapter, SHEET_UX_VERSION } from '../human-control-plane/sheets-adapter.mjs';

const NOW='2026-08-31T04:11:56.012Z';
const execution={id:'execution-acute',jobId:'job-acute',authorizationId:'auth-acute',status:'FAILED',startedAt:'2026-08-31T04:01:00.000Z',updatedAt:NOW,sessionContext:{handoffSession:{pausedAt:NOW,pages:[{url:'https://smartapply.indeed.com/beta/indeedapply/form/review-module',title:'Review application | Indeed'},{url:'https://smartapply.indeed.com/beta/indeedapply/form/post-apply',title:'Se envió tu postulación | Indeed'}]}}};

test('execution-bound Indeed success page is strong confirmation evidence',()=>{const evidence=collectExecutionConfirmationEvidence(execution);assert.equal(evidence.length,1);assert.equal(evidence[0].source,'SUCCESS_PAGE');assert.equal(classifyApplicationReconciliation(evidence).outcome,'APPLIED_CONFIRMED');});

test('Gmail confirmation requires recipient, time, confirmation language and exact job identity',()=>{const message={id:'gmail-1',internalDate:'2026-08-31T04:05:00.000Z',snippet:'Acute Talent recibió tu postulación para Generative AI Engineer / LLM Engineer',headers:{subject:'Postulación enviada',to:'fubifo@gmail.com'}};assert.equal(correlateConfirmationEmail({message,execution,job:{company:'Acute Talent',title:'Generative AI Engineer / LLM Engineer'}})?.source,'CONFIRMATION_EMAIL');assert.equal(correlateConfirmationEmail({message:{...message,id:'gmail-wrong',snippet:'Other Company recibió tu postulación para Data Analyst'},execution,job:{company:'Acute Talent',title:'Generative AI Engineer / LLM Engineer'}}),null);});

test('browser and email confirmations reconcile one lifecycle transition without resubmit',()=>{const events=[],steps=[],calls={finished:0,applied:0},state={...execution};const registry={now:()=>NOW,getApplicationExecution:()=>state,getActiveHumanHandoffForExecution:()=>null,recordWorkflowEvent:event=>{if(!events.some(item=>item.dedupeKey===event.dedupeKey))events.push(event);return{event,duplicate:false};},recordApplicationExecutionStep:(_id,step)=>steps.push(step),finishApplicationExecution:(_id,input)=>{calls.finished++;Object.assign(state,{status:'APPLIED',confirmation:input.confirmation,finishedAt:input.confirmation.observedAt});return state;},markCandidateApplied:()=>calls.applied++};const reconciler=new ApplicationConfirmationReconciler({registry}),email={outcome:'APPLIED_CONFIRMED',source:'CONFIRMATION_EMAIL',messageId:'gmail-1',observedAt:NOW};assert.equal(reconciler.reconcile(state.id,{evidence:[email]}).status,'RECONCILED');assert.equal(reconciler.reconcile(state.id,{evidence:[email]}).status,'ALREADY_APPLIED');assert.equal(calls.finished,1);assert.equal(calls.applied,1);assert.equal(steps.length,1);assert.equal(events.filter(item=>item.eventType==='APPLICATION_MOVED_TO_APPLICATIONS').length,1);});

test('cell diff emits only changed bounded ranges including row removal',()=>{assert.deepEqual(diffMatrices([['A','B'],['one','two'],['old','row']],[['A','B'],['one','changed']],2),[{row:1,startColumn:1,endColumn:2,values:['changed']},{row:2,startColumn:0,endColumn:2,values:['','']}]);});

test('current layout initializes once and identical data projection has zero mutations',async()=>{const adapter=new MemorySheetsAdapter({layoutVersion:SHEET_UX_VERSION});const first=await adapter.initialize();assert.equal(first.structuralMutations,0);await adapter.writeTab('SETTINGS',[['Key','Value','Owner','Description'],['Sheet Projection','DIFF_ONLY','CAREER_OPS','stable']]);const second=await adapter.writeTab('SETTINGS',[['Key','Value','Owner','Description'],['Sheet Projection','DIFF_ONLY','CAREER_OPS','stable']]);assert.equal(second.dataMutations,0);assert.equal(second.structuralMutations,0);});

test('layout version change performs structural work once',async()=>{const adapter=new MemorySheetsAdapter({layoutVersion:'4.4'});assert.ok((await adapter.initialize()).structuralMutations>0);assert.equal((await adapter.initialize()).structuralMutations,0);});
