import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'http';
import { randomUUID } from 'crypto';
import { createGatewayHandler } from '../server.mjs';
import { signRequest } from '../contract.mjs';

const NOW='2026-08-27T20:00:00.000Z',secret='fixture-secret';
const envelope=(overrides={})=>({command_version:'3A.1',command_id:randomUUID(),command_type:'jobs.sync',requested_at:NOW,source:'google_sheet',sheet_id:'sheet',requested_by:'user@example.com',correlation_id:randomUUID(),payload:{},...overrides});
async function withGateway(work){const published=[];const server=http.createServer(createGatewayHandler({secret,topicName:'topic',clock:()=>new Date(NOW),publisher:{async publishMessage(message){published.push(message);return'message-1';}},logger:{info(){},warn(){}}}));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{return await work({url:`http://127.0.0.1:${server.address().port}`,published});}finally{await new Promise(resolve=>server.close(resolve));}}
async function send(url,body,{timestamp=body.requested_at,requestId=body.command_id,signature=null}={}){const raw=JSON.stringify(body);return fetch(`${url}/v1/commands`,{method:'POST',headers:{'content-type':'application/json','x-career-ops-request-id':requestId,'x-career-ops-timestamp':timestamp,'x-career-ops-signature':signature??signRequest({secret,timestamp,requestId,rawBody:raw})},body:raw});}
async function signedPost(url,path,body={}){const rawBody=JSON.stringify(body),requestId=randomUUID(),timestamp=NOW;return fetch(`${url}${path}`,{method:'POST',headers:{'content-type':'application/json','x-career-ops-request-id':requestId,'x-career-ops-timestamp':timestamp,'x-career-ops-signature':signRequest({secret,timestamp,requestId,rawBody})},body:rawBody});}

test('accepts signed allowlisted command and publishes contract attributes',()=>withGateway(async({url,published})=>{const body=envelope();const response=await send(url,body);assert.equal(response.status,202);assert.equal((await response.json()).command_id,body.command_id);assert.equal(published.length,1);assert.equal(published[0].attributes.command_type,'jobs.sync');}));
test('rejects invalid signature and payload mutation',()=>withGateway(async({url,published})=>{const body=envelope();const raw=JSON.stringify(body);const signature=signRequest({secret,timestamp:NOW,requestId:body.command_id,rawBody:raw});body.payload={mutated:true};assert.equal((await send(url,body,{signature})).status,401);assert.equal(published.length,0);}));
test('rejects stale timestamp, unknown commands, missing auth, and replay',()=>withGateway(async({url})=>{const stale=envelope({requested_at:'2026-08-27T19:00:00.000Z'});assert.equal((await send(url,stale)).status,401);const unknown=envelope({command_type:'run_shell'});assert.equal((await send(url,unknown)).status,400);assert.equal((await fetch(`${url}/v1/commands`,{method:'POST',body:'{}'})).status,401);const valid=envelope();assert.equal((await send(url,valid)).status,202);assert.equal((await send(url,valid)).status,409);}));
test('health reveals no secret',()=>withGateway(async({url})=>{const response=await fetch(`${url}/health`);assert.equal(response.status,200);const text=await response.text();assert.doesNotMatch(text,/fixture-secret/);assert.match(text,/healthy/);}));
test('signed pull and ack proxy Pub/Sub without local Google credentials',async()=>{const calls=[];const subscriber={async pull(){calls.push('pull');return[{ack_id:'ack-1',message_id:'message-1',data:Buffer.from('{}').toString('base64')}];},async ack(id){calls.push(`ack:${id}`);},async nack(id){calls.push(`nack:${id}`);}};const server=http.createServer(createGatewayHandler({secret,topicName:'topic',publisher:{publishMessage:async()=>''},subscriber,clock:()=>new Date(NOW),logger:{info(){},warn(){}}}));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{const url=`http://127.0.0.1:${server.address().port}`;const pull=await signedPost(url,'/v1/subscriptions/pull');assert.equal(pull.status,200);assert.equal((await pull.json()).messages[0].ack_id,'ack-1');const ack=await signedPost(url,'/v1/subscriptions/ack',{ack_id:'ack-1',disposition:'ack'});assert.equal(ack.status,200);assert.deepEqual(calls,['pull','ack:ack-1']);}finally{await new Promise(resolve=>server.close(resolve));}});
