export const HUMAN_ATTENTION_VERSION = '3F.1';

export const ATTENTION_TYPES = Object.freeze([
  'DECISION_REQUIRED',
  'REVIEW_REQUIRED',
  'ANSWER_REQUIRED',
  'APPROVAL_REQUIRED',
  'VERIFICATION_REQUIRED',
  'FOLLOW_UP_REQUIRED',
  'EXTERNAL_ACTION_REQUIRED',
]);

export const ATTENTION_ORDER = Object.freeze([
  'VERIFICATION_REQUIRED',
  'ANSWER_REQUIRED',
  'APPROVAL_REQUIRED',
  'REVIEW_REQUIRED',
  'DECISION_REQUIRED',
  'FOLLOW_UP_REQUIRED',
  'EXTERNAL_ACTION_REQUIRED',
]);

export const VERIFICATION_RESOLUTIONS = Object.freeze([
  'CONFIRMED_APPLIED',
  'NOT_APPLIED',
  'KEEP_UNKNOWN',
]);

export const HUMAN_INPUT_ERROR = Object.freeze({
  human_resolution: 'Human Resolution must be CONFIRMED_APPLIED, NOT_APPLIED or KEEP_UNKNOWN.',
});

