export const WORKFLOW_EVENT_VERSION = '3B.3';

export const WORKFLOW_AGGREGATE_TYPES = Object.freeze([
  'COMMAND', 'JOB', 'APPLICATION', 'ENRICHMENT', 'COMMUNITY', 'RESEARCH',
  'CONTACT', 'OUTREACH', 'SHEET_SYNC', 'NOTIFICATION', 'OPERATIONAL_RUN', 'WORK_ITEM',
]);

export const WORKFLOW_EVENT_TYPES = Object.freeze([
  'COMMAND_RECEIVED', 'COMMAND_STARTED', 'COMMAND_COMPLETED', 'COMMAND_FAILED',
  'JOB_DECISION_IMPORTED', 'JOB_REJECTED', 'JOB_HELD', 'JOB_NEXT_STAGE_REQUESTED',
  'JOB_ENTERED_ACTIVE_SET', 'JOB_CARRIED_OVER', 'JOB_SUPERSEDED', 'JOB_REMOVED_FROM_ACTIVE',
  'JOB_PINNED', 'JOB_UNPINNED',
  'ENRICHMENT_QUEUED', 'ENRICHMENT_STARTED', 'ENRICHMENT_COMPLETED',
  'ENRICHMENT_BLOCKED', 'ENRICHMENT_FAILED',
  'EVALUATION_COMPLETED', 'PACKAGE_GENERATED', 'PACKAGE_SUPERSEDED',
  'APPLICATION_APPROVED', 'APPLICATION_HUMAN_ANSWER_PROVIDED',
  'APPLICATION_EXECUTION_STARTED', 'APPLICATION_SUBMIT_ATTEMPTED',
  'APPLICATION_NEEDS_HUMAN', 'APPLICATION_CONFIRMATION_OBSERVED', 'APPLICATION_CONFIRMED', 'APPLICATION_MOVED_TO_APPLICATIONS',
  'APPLICATION_VERIFICATION_UNKNOWN', 'APPLICATION_FAILED', 'APPLICATION_CANCELLED',
  'APPLICATION_HUMAN_CONFIRMED', 'APPLICATION_HUMAN_NOT_APPLIED', 'APPLICATION_VERIFICATION_RETAINED',
  'APPLICATION_FOLLOW_UP_UPDATED',
  'APPLICATION_INTERVIEW', 'APPLICATION_REJECTED', 'APPLICATION_OFFER',
  'APPLICATION_HIRED', 'APPLICATION_WITHDRAWN', 'APPLICATION_STATUS_CORRECTED',
  'HUMAN_HANDOFF_CREATED', 'HUMAN_HANDOFF_RESOLVED', 'APPLICATION_RESUME_STARTED', 'APPLICATION_RESUMED',
  'OUTREACH_AUTHORIZED', 'OUTREACH_SCHEDULED', 'OUTREACH_STARTED', 'OUTREACH_SENT',
  'OUTREACH_FAILED', 'OUTREACH_VERIFICATION_REQUIRED', 'OUTREACH_EXTERNAL_ACTION_REQUIRED',
  'OUTREACH_RESPONSE_RECEIVED',
  'RESEARCH_NEED_CREATED', 'RESEARCH_NEED_RESOLVED', 'RESEARCH_NEED_BLOCKED',
  'COMMUNITY_DISCOVERED', 'COMMUNITY_DECISION_IMPORTED', 'COMMUNITY_JOIN_REQUESTED',
  'COMMUNITY_JOIN_CONFIRMED', 'COMMUNITY_JOIN_PENDING', 'COMMUNITY_NEEDS_HUMAN',
  'COMMUNITY_SUPPRESSED', 'COMMUNITY_MONITORING_COMPLETED',
  'SHEET_SYNC_STARTED', 'SHEET_SYNC_COMPLETED', 'SHEET_SYNC_FAILED',
  'NOTIFICATION_REQUIRED', 'NOTIFICATION_SENT', 'NOTIFICATION_DISABLED', 'NOTIFICATION_FAILED',
  'OPERATIONAL_RUN_STARTED', 'OPERATIONAL_RUN_COMPLETED', 'OPERATIONAL_RUN_PARTIAL',
  'OPERATIONAL_RUN_FAILED', 'OPERATIONAL_SIGNAL_DETECTED', 'OPERATIONAL_RECOVERY_STARTED',
  'OPERATIONAL_RECOVERY_SUCCEEDED', 'OPERATIONAL_RECOVERY_FAILED', 'OPERATIONAL_ESCALATED',
  'WORKFLOW_TIMELINE_BASELINED',
  'WORK_QUEUED', 'WORKER_WAKE_REQUESTED', 'WORK_CLAIMED', 'WORK_RESUMED',
  'WORKER_RECOVERED', 'HUMAN_QUESTION_CREATED', 'HUMAN_QUESTION_ANSWERED',
]);

export const WORKFLOW_EVENT_SOURCES = Object.freeze([
  'sheet', 'command_gateway', 'command_subscriber', 'daily_core', 'browser_research',
  'application_enrichment', 'application_execution', 'outreach_execution', 'facebook', 'system',
]);

export const WORKFLOW_ACTOR_TYPES = Object.freeze(['HUMAN', 'SYSTEM', 'EXTERNAL_PLATFORM']);

export const EVENT_STAGE = Object.freeze({
  COMMAND_RECEIVED:'SYSTEM', COMMAND_STARTED:'SYSTEM', COMMAND_COMPLETED:'SYSTEM', COMMAND_FAILED:'SYSTEM',
  JOB_DECISION_IMPORTED:'DECIDE', JOB_REJECTED:'DECIDE', JOB_HELD:'DECIDE', JOB_NEXT_STAGE_REQUESTED:'DECIDE',
  JOB_ENTERED_ACTIVE_SET:'DISCOVER', JOB_CARRIED_OVER:'DISCOVER', JOB_SUPERSEDED:'DISCOVER', JOB_REMOVED_FROM_ACTIVE:'DISCOVER', JOB_PINNED:'DECIDE', JOB_UNPINNED:'DECIDE',
  ENRICHMENT_QUEUED:'PREPARE', ENRICHMENT_STARTED:'PREPARE', ENRICHMENT_COMPLETED:'PREPARE', ENRICHMENT_BLOCKED:'PREPARE', ENRICHMENT_FAILED:'PREPARE',
  EVALUATION_COMPLETED:'PREPARE', PACKAGE_GENERATED:'PREPARE', PACKAGE_SUPERSEDED:'PREPARE',
  APPLICATION_APPROVED:'APPLY', APPLICATION_HUMAN_ANSWER_PROVIDED:'APPLY', APPLICATION_EXECUTION_STARTED:'APPLY', APPLICATION_SUBMIT_ATTEMPTED:'APPLY', APPLICATION_NEEDS_HUMAN:'APPLY', APPLICATION_CONFIRMATION_OBSERVED:'TRACK_LEARN', APPLICATION_CONFIRMED:'TRACK_LEARN', APPLICATION_MOVED_TO_APPLICATIONS:'TRACK_LEARN', APPLICATION_VERIFICATION_UNKNOWN:'APPLY', APPLICATION_FAILED:'APPLY', APPLICATION_CANCELLED:'APPLY', APPLICATION_HUMAN_CONFIRMED:'TRACK_LEARN', APPLICATION_HUMAN_NOT_APPLIED:'APPLY', APPLICATION_VERIFICATION_RETAINED:'APPLY', APPLICATION_FOLLOW_UP_UPDATED:'TRACK_LEARN', APPLICATION_INTERVIEW:'TRACK_LEARN', APPLICATION_REJECTED:'TRACK_LEARN', APPLICATION_OFFER:'TRACK_LEARN', APPLICATION_HIRED:'TRACK_LEARN', APPLICATION_WITHDRAWN:'TRACK_LEARN', APPLICATION_STATUS_CORRECTED:'TRACK_LEARN',
  HUMAN_HANDOFF_CREATED:'APPLY', HUMAN_HANDOFF_RESOLVED:'APPLY', APPLICATION_RESUME_STARTED:'APPLY', APPLICATION_RESUMED:'APPLY',
  OUTREACH_AUTHORIZED:'APPLY', OUTREACH_SCHEDULED:'APPLY', OUTREACH_STARTED:'APPLY', OUTREACH_SENT:'TRACK_LEARN', OUTREACH_FAILED:'APPLY', OUTREACH_VERIFICATION_REQUIRED:'APPLY', OUTREACH_EXTERNAL_ACTION_REQUIRED:'APPLY', OUTREACH_RESPONSE_RECEIVED:'TRACK_LEARN',
  RESEARCH_NEED_CREATED:'PREPARE', RESEARCH_NEED_RESOLVED:'PREPARE', RESEARCH_NEED_BLOCKED:'PREPARE',
  COMMUNITY_DISCOVERED:'COMMUNITY', COMMUNITY_DECISION_IMPORTED:'COMMUNITY', COMMUNITY_JOIN_REQUESTED:'COMMUNITY', COMMUNITY_JOIN_CONFIRMED:'COMMUNITY', COMMUNITY_JOIN_PENDING:'COMMUNITY', COMMUNITY_NEEDS_HUMAN:'COMMUNITY', COMMUNITY_SUPPRESSED:'COMMUNITY', COMMUNITY_MONITORING_COMPLETED:'COMMUNITY',
  SHEET_SYNC_STARTED:'SYSTEM', SHEET_SYNC_COMPLETED:'SYSTEM', SHEET_SYNC_FAILED:'SYSTEM', NOTIFICATION_REQUIRED:'SYSTEM', NOTIFICATION_SENT:'SYSTEM', NOTIFICATION_DISABLED:'SYSTEM', NOTIFICATION_FAILED:'SYSTEM', OPERATIONAL_RUN_STARTED:'SYSTEM', OPERATIONAL_RUN_COMPLETED:'SYSTEM', OPERATIONAL_RUN_PARTIAL:'SYSTEM', OPERATIONAL_RUN_FAILED:'SYSTEM', OPERATIONAL_SIGNAL_DETECTED:'SYSTEM', OPERATIONAL_RECOVERY_STARTED:'SYSTEM', OPERATIONAL_RECOVERY_SUCCEEDED:'SYSTEM', OPERATIONAL_RECOVERY_FAILED:'SYSTEM', OPERATIONAL_ESCALATED:'SYSTEM', WORKFLOW_TIMELINE_BASELINED:'SYSTEM',
  WORK_QUEUED:'SYSTEM', WORKER_WAKE_REQUESTED:'SYSTEM', WORK_CLAIMED:'SYSTEM', WORK_RESUMED:'SYSTEM', WORKER_RECOVERED:'SYSTEM', HUMAN_QUESTION_CREATED:'APPLY', HUMAN_QUESTION_ANSWERED:'APPLY',
});

const EVENT_SET = new Set(WORKFLOW_EVENT_TYPES);
const AGGREGATE_SET = new Set(WORKFLOW_AGGREGATE_TYPES);
const SOURCE_SET = new Set(WORKFLOW_EVENT_SOURCES);
const ACTOR_SET = new Set(WORKFLOW_ACTOR_TYPES);

export function validateWorkflowEvent(input = {}) {
  const text = (value, name) => { const result = String(value ?? '').trim(); if (!result) throw new TypeError(`${name} is required`); return result; };
  const eventType = text(input.eventType, 'eventType');
  const aggregateType = text(input.aggregateType, 'aggregateType');
  if (!EVENT_SET.has(eventType)) throw new TypeError(`unknown workflow event type: ${eventType}`);
  if (!AGGREGATE_SET.has(aggregateType)) throw new TypeError(`unknown workflow aggregate type: ${aggregateType}`);
  if (!SOURCE_SET.has(input.source)) throw new TypeError(`unknown workflow event source: ${input.source}`);
  if (input.actorType != null && !ACTOR_SET.has(input.actorType)) throw new TypeError(`unknown workflow actor type: ${input.actorType}`);
  if (input.payload != null && (typeof input.payload !== 'object' || Array.isArray(input.payload))) throw new TypeError('payload must be an object');
  if (input.metadata != null && (typeof input.metadata !== 'object' || Array.isArray(input.metadata))) throw new TypeError('metadata must be an object');
  return { ...input, eventType, aggregateType, aggregateId:text(input.aggregateId,'aggregateId'), correlationId:text(input.correlationId,'correlationId') };
}
