import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'http';
import { randomUUID } from 'crypto';
import { createBrokerHandler, mintDelegatedToken, signBrokerRequest } from '../server.mjs';
const NOW='2026-08-30T18:00:00.000Z';
const response=(body,{ok=true,status=200}={})=>({ok,status,json:async()=>body});
test('mints a new DWD token through metadata identity and IAM signBlob',async()=>{const calls=[];const result=await mintDelegatedToken({serviceAccountEmail:'agent@project.iam.gserviceaccount.com',subject:'brunova@brunova.mx',scopes:['sheets'],clock:()=>new Date(NOW),fetchImpl:async(url,options={})=>{calls.push({url:String(url),options});if(String(url).startsWith('http://metadata'))return response({access_token:'metadata'});if(String(url).includes(':signBlob'))return response({signedBlob:Buffer.from('signature').toString('base64')});return response({access_token:'delegated',expires_in:3600});}});assert.equal(result.access_token,'delegated');assert.equal(result.subject,'brunova@brunova.mx');assert.equal(calls.length,3);});
test('broker requires a fresh signed request and exposes no token in health',async()=>{const secret='fixture',server=http.createServer(createBrokerHandler({secret,serviceAccountEmail:'agent@project.iam.gserviceaccount.com',subject:'brunova@brunova.mx',clock:()=>new Date(NOW),fetchImpl:async url=>String(url).startsWith('http://metadata')?response({access_token:'metadata'}):String(url).includes(':signBlob')?response({signedBlob:Buffer.from('sig').toString('base64')}):response({access_token:'delegated'}) ,logger:{error(){}}}));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{const base=`http://127.0.0.1:${server.address().port}`,health=await fetch(`${base}/health`);assert.doesNotMatch(await health.text(),/fixture|delegated/);const requestId=randomUUID(),signature=signBrokerRequest({secret,timestamp:NOW,requestId});const token=await fetch(`${base}/v1/workspace-token`,{method:'POST',headers:{'x-career-ops-request-id':requestId,'x-career-ops-timestamp':NOW,'x-career-ops-signature':signature}});assert.equal(token.status,200);assert.equal((await token.json()).subject,'brunova@brunova.mx');assert.equal((await fetch(`${base}/v1/workspace-token`,{method:'POST'})).status,401);}finally{await new Promise(resolve=>server.close(resolve));}});
