export const APPLICATION_ACTIVATION_VERSION = '4.3';

export const OUTREACH_STRATEGIES = Object.freeze([
  'OUTREACH_RECOMMENDED', 'OUTREACH_OPTIONAL', 'NO_OUTREACH', 'OUTREACH_BLOCKED', 'MANUAL_OUTREACH_RECOMMENDED',
]);

export const OUTREACH_CHANNELS = Object.freeze([
  'RECRUITER_EMAIL', 'HIRING_MANAGER_EMAIL', 'LINKEDIN_PROFILE',
  'GENERAL_RECRUITING', 'PLATFORM_MESSAGE', 'NONE',
]);

export const OUTREACH_TIMINGS = Object.freeze([
  'BEFORE_APPLICATION', 'IMMEDIATELY_AFTER_APPLICATION', 'NEXT_BUSINESS_DAY',
  'FOLLOW_UP_AFTER_N_DAYS', 'NONE',
]);

export const OUTREACH_DECISIONS = Object.freeze([
  'NO_ACTION', 'APPROVE_OUTREACH', 'SKIP_OUTREACH', 'HOLD',
]);

export const OUTREACH_OUTCOMES = Object.freeze([
  'UNKNOWN', 'NO_RESPONSE', 'REPLIED', 'RECRUITER_SCREEN', 'INTERVIEW',
  'REFERRED', 'NEGATIVE',
]);
